### ISSUE TITLE
ContextSharing not working for different modules

### ISSUE THREAD

**Issue by reh2ur** [TanStack/query#2810] opened 2021-10-19 08:35 UTC
**Describe the bug**
When using the `QueryClientProvider` in an npm package and requiring the query client via `useQueryClient` in the consumer app, I am always getting the following error:
```
Error: No QueryClient set, use QueryClientProvider to set one
```

It seems like the logic for getting the shared context is broken.

**Expected behavior**
Using the `useQueryClient` should check for the shared `ReactQueryClientContext` and use it if existing.

**Additional context**
With #1912 the context sharing was disabled by default, and seems to have been disabled at all.
It seems like the `QueryClientSharingContext` is always false, as it is initialized with that value:
https://github.com/tannerlinsley/react-query/blob/05a8057e2be64915d2a12b716d8131f113598dbd/src/react/QueryClientProvider.tsx#L12
https://github.com/tannerlinsley/react-query/blob/05a8057e2be64915d2a12b716d8131f113598dbd/src/react/QueryClientProvider.tsx#L34

Shouldn't the context be initialized with whether there is a shared context or a boolean value, passed to the `useQueryClient` hook?

**Comment by TkDodo** [comment] 2021-10-19 09:06
right, I think you'd need a `QueryClientProvider` to turn contextSharing on, which kinda defeats the purpose 🤔 . Can you create a codesandbox example that works with a version _before_ #1912 was merged and doesn't work with the latest version? Thanks.

**Closed as completed** 2021-10-19 09:33 UTC

**Comment by reh2ur** [comment] 2021-10-19 20:12
We are experimenting with extracting shared logic from multiple NextJS projects into an internally used library. I am trying to create a reusable Wrapper component that encapsulates UI elements as well as support for data fetching. This `<Wrapper />` would take care of rendering the `QueryClientProvider` with an appropriate client, so that the consumer could just call `useQuery` without having to deal with the actual client.

The library has `react-query` as a peer dependency, which is why the `useQuery` hooks of the consumer app and the `QueryClientProvider` of our shared module habe the same `react-query` instances.

**Comment by vsylvestre** [comment] 2021-11-30 17:10
@reh2ur I'd be curious to have more details as to how you fixed this, since I'm in a very similar situation.

We have a “shared library” which is imported as a package in various projects within a monorepo. I‘m trying to transfer what we call the `DataFetchingLayer` component, which contains the logic to instantiate the query client and wraps everything with `QueryClientProvider`, into that library to be shared by the different projects. However, I get the same error you mentioned in your OP, caused by the use of `useQuery` in the projects that import the library. The only way I can fix this is by having _another_ `QueryClientProvider` on the projects’ side, which kind of defeats the purpose of having it in a shared library.

Similarly to your situation, we have `react-query` as a peer dependency in the library. But the version is the same as that of the projects‘. They‘re all bundled with Webpack, so I added `react-query` as an “external” in my Webpack config, and that didn‘t help. I tried bumping  `react-query` to the latest version for all of them, but that didn‘t work either.

Did you happen to do anything else other than making sure that the versions matched?

**Comment by scottdickerson** [comment] 2022-06-10 14:25
this is exactly what we're trying and this is still happening for me as well @vsylvestre , details here: https://github.com/TanStack/query/discussions/3697

I checked the `react-query` versions, they are the same between consumer and provider as well, `peerDependencies` and `devDependencies` on the MFE provider of `react-query: 3.39.1`, and `dependencies` on the consumer side of `react-query: 3.39.1`

**Comment by TkDodo** [comment] 2022-06-10 15:09
you'd need to provide a reproducible example of some sorts please.
also, in v4, there is the option to pass a custom query context for scoped providers. Have a look at the example in the migration guide: https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#custom-contexts-for-multiple-providers

**Comment by petejodo** [comment] 2022-08-12 03:56
I do think context sharing is broken and that's because the [QueryClientSharingContext](https://github.com/TanStack/query/blob/main/packages/react-query/src/QueryClientProvider.tsx#L15) is created across all instances of react-query and so the sharing context itself isn't shared. That context is the way the value passed in for [`contextSharing` in QueryClientProvider](https://github.com/TanStack/query/blob/main/packages/react-query/src/QueryClientProvider.tsx#L74) by passing it into that [shared context's provider](https://github.com/TanStack/query/blob/main/packages/react-query/src/QueryClientProvider.tsx#L86).

That's how [useQueryClient knows to use context sharing](https://github.com/TanStack/query/blob/main/packages/react-query/src/QueryClientProvider.tsx#L44)

[Here's what a fix could maybe look like](https://github.com/petejodo/react-query/commit/5849b11c69fea33892e3528c000999aa7266e7b5)

**Comment by TkDodo** [comment] 2022-08-12 17:50
I'm honestly pretty unsure what contextSharing is and what it's supposed to be doing. Is it necessary / useful to anyone? Isn't the new feature in v4 enough where you can pass a custom context around? If so, I would be in favour of deprecating it ...

**Comment by numbers1311407** [comment] 2022-09-10 03:04
I just puzzled over the source around `contextSharing` for a while trying to make sense of how it could possibly be useful, with the conclusion that it just isn't, or I was missing something simple.  This thread would suggest the former.

The *context* is shareable (so the name fits), but each app still needs to live under a context provider, which must insantiate and provide a new query client.  So while you can share *context*, you can't share the client, which makes this seem pointless.

Context mismatch due to duplicate modules is a very easy pitfall for MFE style apps but it's already a solved problem by ensuring the context creator is a shared singleton / peer dep.  This is an issue for *any* family of React packages that provide/consume context.  Am I missing something here or is contextSharing just attempting to (re)solve that problem?

**Comment by ecyrbe** [comment] 2022-10-02 20:34
> you'd need to provide a reproducible example of some sorts please. also, in v4, there is the option to pass a custom query context for scoped providers. Have a look at the example in the migration guide: https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#custom-contexts-for-multiple-providers

So like i said on [V5 discussion](https://github.com/TanStack/query/discussions/4252#discussioncomment-3782876) context sharing is used in the context of microfrontends.

**Big picture here :**
Context sharing allows users of microfrontend to evoid handling context instanciation manually and run into issues of which one should share the context. More elaborate answer on this in v5 discussion.

Now context isolation is an option if handled by each microfrontend to override the default react-query context instance. 
But it would  be bad for performance reasons. Users of microfrontend will indeed prefer to share context to take advantage of shared cache and evoid duplicate request of common server states. For this to work, you then need to have some kind of key normalisation in your project.

So you need to either: 
- activate today shared context for react to be happy else react tells you that context already exists (react need to be a shared singleton library to work properly in microfrontends)
- instanciate an isolated context in your microfrontend (haven't tried this option yet, performance concerns)
- instanciate a shared context in a singleton shared library (with Module Federation ) that is a superset of react-query. This common library would need to do what react-query does today with context sharing. So reinvating the wheel in each project with the possibility of doing it badly. (haven't tried this option yet)

**Comment by TkDodo** [comment] 2022-10-03 09:20
@ecyrbe I'm not entirely sure how you've setup microfrontends, but why wouldn't the hosting application just create the QueryClient and the Provider, and it would then be picked up by the microfrontends when they call `useQueryClient` ?

Are the microfrontends mountings themselves to different roots? If so, creating the context and passing it to the microfrontends as shown in the custom-contexts docs should work? Albeit a bit more boilerplate as every call to useQuery / useQueryClient would need to use that context ...

I just have the feeling that taking the context and putting it onto the window object is also a bit dirty.

**Comment by ecyrbe** [comment] 2022-10-04 04:14
@TkDodo  
- First a quick higlight : when using a library in a micro frontend you need to either use it in isolation or as a shared one. And i agree that you usually want to use isolation first. But for tanstack query, you usually want to use it shared. Indeed, Tanstack query is server state that you usually want to share for perf reasons, while application state is what you want to isolate.
- Like i said. React/tanstack query should not be a dependancy of your host. Because your host is the one that should be agnostic to frameworks/libs. So you can't import react/tanstack in the host to share react query, this would break isolation  
-What will be done if you deprecate shared state, is the third option i listed. no choice. It would be to let micro frontend users handle the shared state themselves. I'm not saying it's impossible to do. But it will certainly be a big pain point compared to what is available now.
- Now about the solutions on how to share state inside a shared singleton library. There are many options if you know what technology is used for doing micro frontends, if there is a cross communication channel setup in the microfrontends, but tanstack query can't possibly know any of that, the easiest way of sharing state is indeed to use the global this object.

**Comment by TkDodo** [comment] 2022-10-07 14:37
> First a quick higlight 

I understand, make sense.

> So you can't import react/tanstack in the host to share react query, this would break isolation

That i don't understand so much. If I want to share a QueryClient between MFEs, why is that not the responsibility of the hosting app? It doesn't need to know about react - it just needs a dependency to `@tanstack/query-core`, where the queryClient lives.

Isn't it in general a bit magical that the first MFE that mounts decides what the context is? Can that not lead to random behaviour?

**Comment by ecyrbe** [comment] 2022-10-07 16:32
The issue seems to be with the context setup more than query client instanciation.  
Meaning, if i only have 2 out 10 MFE that use react, i only want to setup context on those. Not on the host. Without shared context, i'll have to create a shared context myself on a shared singleton library, a bit more work, but doable.
  
So, If you don't want to maintain this i'll find a way to do the necessary on my app. Don't worry.

**Comment by TkDodo** [comment] 2022-10-09 18:53
@ecyrbe if there is a legit use-case for microfrontends that is not easily solvable otherwise, this could in fact be a good feature. It's just not clear to me (and others) what it does exactly. You've done a good job explaining it :)

what I still don't quite understand is: We are not sharing the `QueryClient` - merely the React `context`. so how does this share data between MFEs?

**Comment by ecyrbe** [comment] 2022-10-09 19:12
Oh, maybe i'm misstaken too. Because i thought that using shared context was sharing QueryClient. Can one context handle many QueryClients ?

**Comment by TkDodo** [comment] 2022-10-09 19:14
> Can one context handle many QueryClients ?

no 😅. In order to share data, you'd need to use the same queryClient

**Comment by ecyrbe** [comment] 2022-10-09 19:19
I should take a look at the current code implementation then. Because, i have shared context setup on all mfe, doing nothing special with query client and expecting it to use the first one instanciated. at least last time i cheked, that's what i thought was happening.
I i'll poke something to have definitive view of what current code does and let you know.

**Comment by TkDodo** [comment] 2022-10-09 20:36
Here is a quick codesandbox reproduction that renders the same App twice with two different mountpoints. Each App gets a `new QueryClient()` passed in, but the context is shared.

https://codesandbox.io/s/tender-dust-z7695p?file=/src/index.jsx

As you can see in the `random` print, the data is _not_ shared between the two.

If you go the devtools and log `window.ReactQueryClientContext`, it will show an object that looks something like this:

```
$$typeof: Symbol(react.context)
Consumer: {$$typeof: Symbol(react.context), _context: {…}, …}
Provider: {$$typeof: Symbol(react.provider), _context: {…}}
_currentRenderer: {}
_currentRenderer2: null
_currentValue: undefined
_currentValue2: undefined
_defaultValue: null
_globalName: null
_threadCount: 0
[[Prototype]]: Object
```

**Comment by cmacdonnacha** [comment] 2023-11-14 22:48
> Here is a quick codesandbox reproduction that renders the same App twice with two different mountpoints. Each App gets a `new QueryClient()` passed in, but the context is shared.
> 
> https://codesandbox.io/s/tender-dust-z7695p?file=/src/index.jsx
> 
> As you can see in the `random` print, the data is _not_ shared between the two.
> 
> If you go the devtools and log `window.ReactQueryClientContext`, it will show an object that looks something like this:
> 
> ```
> $$typeof: Symbol(react.context)
> Consumer: {$$typeof: Symbol(react.context), _context: {…}, …}
> Provider: {$$typeof: Symbol(react.provider), _context: {…}}
> _currentRenderer: {}
> _currentRenderer2: null
> _currentValue: undefined
> _currentValue2: undefined
> _defaultValue: null
> _globalName: null
> _threadCount: 0
> [[Prototype]]: Object
> ```

Hey @TkDodo 

Sorry, this is going back a year. We have a scenario where we do want to share the data between both Apps. Any idea how this can be achieved?

**Comment by TkDodo** [comment] 2023-11-15 07:02
In v5, you can pass a queryClient directly to all hooks as second argument. You can "share" that client however you want to, but we are not doing anything like that.

**Comment by cmacdonnacha** [comment] 2023-11-15 10:13
> In v5, you can pass a queryClient directly to all hooks as second argument. You can "share" that client however you want to, but we are not doing anything like that.

We basically have a legacy Rails app and have replaced the traditional views with React based pages instead. However, it means that each high level component or page is essentially it's own app. For example, we have:

- Header
- Sidenav
- Page content
- Footer

Because each of these is a separate app, they all create their own `new QueryClient`. So I would love to have a way to share a single query client with all 4 so we can share data between them. For example when I cause a mutation in the page content, I want the header to reflect that. The hack right now is to reload the browser when we need data to update, but it's not ideal UX.

I know this is not your problem but I was wondering if you had any thoughts? Share the client via local storage? Use the `window`?

**Comment by TkDodo** [comment] 2023-11-15 12:05
>  import queryClient from a shared module 

yep this
