### ISSUE TITLE
Unable to use react-query when hooks are created in separate library

### ISSUE THREAD

**Issue by SoftMemes** [TanStack/query#3595] opened 2022-05-09 08:51 UTC
### Describe the bug

I have a monorepo with yarn 3 workspaces consisting of the following (as well as other components):

- `contracts` which uses Orval to create typed react-query hooks from OpenAPI
- `ui`, a next.js project that has a workspace dependency on contracts and is using above hooks

The only direct dependencies on react-query are through `contracts`, my UI project does not directly use react-query.

I'm now running into a few issues to do with module resolution, and am not sure how much of this relates to yarn, workspaces, react-query, or next magic.

# React-query cannot find QueryProvider

If I make react-query a _peer_ dependency of `contracts`, then initialize `react-query` in my next project (set a query provider, etc), then the hooks that use react-query under the hood from `contracts` do not find the QueryClient. It appears to "see" its own version of react-query even though this is a peer dependency of contracts and I provide it as a direct dependency in ui.

I am able to work around this by having `contracts` instead directly depend on `react-query`, and re-export the symbols from react-query (`export * from 'react-query'). This appears to give the hooks in `contracts` access to the same react-query and the context / query provider is found.

... or at least it was. Without any meaningful changes (I'm working on pinning down the exact change), I am no longer able to do it this way, as react-query now fails to find `react`. Inside the compiled code of `react-query`, I am getting `React` as an undefined symbol and this line blows up `var defaultContext = /*#__PURE__*/React.createContext(undefined);` iin react/QueryClientProvider.js

I appreciate that this isn't much to go on, but in general, what is the recommended method for providing custom hooks based on react-query in a library in terms of dependencies and configuration of the query client?

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Build a library that leverages react-query in custom hooks with react-query as a peer dependency
2. Use the library from above in a different project, providing react-query as a direct dependency
3. Configure react-query with a QueryClientProvider in the dom where the hooks from 1 are being used

### Expected behavior

React-query can "see" the context and query provider wired up in the react DOM, even when using peer dependencies and the react-query library is provided as a dependency form the parent project.

### How often does this bug happen?

Every time

### Platform

- OS: Ubuntu 20
- Yarn: 3.2.0
- Next.js: 12.1.6

### react-query version

3.39.0

### TypeScript version

4.6.4

**Comment by TkDodo** [comment] 2022-05-15 10:57
> I appreciate that this isn't much to go on, but in general, what is the recommended method for providing custom hooks based on react-query in a library in terms of dependencies and configuration of the query client?

if you want a shared scope, meaning that the library uses the same context / client as the application that includes it, I would do it like you've described (I think):
- have the `lib` define `react-query` as `peerDependency`
- have the `app` create the `queryClient` and the `QueryClientProvider`.

the `useQuery` calls in the lib _should_ just pick up that client. If that's not the case, you likely have either two versions of react-query or two versions of react around.

if you want an isolated scope, I would take a look at the [custom context feature for v4](https://react-query-beta.tanstack.com/guides/migrating-to-react-query-4#custom-contexts-for-multiple-providers).

**Comment by TkDodo** [comment] 2022-06-04 07:33
Any updates here? Is this still an issue?

**Comment by nctay** [comment] 2022-06-26 22:10
Having same issue with **turborepo** monorepo setup, extracting queries to different package causes it.

**Comment by TkDodo** [comment] 2022-06-27 06:10
@nctay can you link to an example repo that has the issue please?

**Comment by petercpwong** [comment] 2022-07-23 10:28
Having the same issue as well with a NextJS pnpm monorepo setup, even after upgrading to react-query v4. Had to pass in `defaultContext` to every single hook to get it to work. I'm also using `next-transpile-modules` so that could be what's causing the issue.

It works flawlessly with a vite pnpm monorepo setup though.

**Comment by stamahto** [comment] 2022-07-24 17:13
I have same issue too

**Comment by TkDodo** [comment] 2022-07-24 17:52
It's honestly not very helpful stating that you have the issue too without providing a minimal reproduction that we can look into. So far, no one has created a reproduction, so there is nothing I can look into.
I'm gonna close this now, feel free to reopen once you can share a reproduction.

**Closed by TkDodo** 2022-07-24 17:52 UTC

**Comment by mverissimo** [comment] 2022-07-24 20:18
I faced this issue too, you need to check if have the equal version of react and react-query and both packages.

**Comment by stamahto** [comment] 2022-07-25 05:38
> I faced this issue too, you need to check if have the equal version of react and react-query and both packages.

I do, still not working. I´m gonna have to learn publishing packages into npmjs and create reproduction case. It will take me some time, but I hope it will be worthy.

**Comment by SoftMemes** [comment] 2022-07-25 06:34
Hi,

Not a repro, and I'm travelling so will be a brief message from the phone, but I know at least what caused this now. Using yarn 3 with a pnpm style repo (this may apply to other setups but this is where I've seen it), a dependency will only be shared if it matches exactly. This means that the same version has to be resolved which is easy enough to guarantee with version ranges but also critically, the same dependencies need to have been resolved.

This interacts with in particular dev dependencies. If the project A dependends on library B, both which use a third party package C (for example react query), but A and B have direct dependencies in such a way that the dev dependencies of C are fulfilled by different versions, then A and B will see different instances of C.

The way to check this is to compare where the symlink for C is pointing in node modules for A vs B, the compare the node modules in turn for the instance of C used by A vs C used by B, and tweak dependencies of each until they match perfectly.

**Comment by marissync** [comment] 2022-07-27 13:58
> Having the same issue as well with a NextJS pnpm monorepo setup, even after upgrading to react-query v4. Had to pass in `defaultContext` to every single hook to get it to work. I'm also using `next-transpile-modules` so that could be what's causing the issue.
> 
> It works flawlessly with a vite pnpm monorepo setup though.


How did you do that? Facing same issue in next.js

**Comment by petercpwong** [comment] 2022-07-28 01:40
@marissync The `useQuery` hook accepts a `context` property. Just pass in the `defaultContext` exported by react query.

```
import { defaultContext, useQuery } from '@tanstack/react-query';

useQuery({ context: defaultContext });
```

**Comment by marissync** [comment] 2022-07-28 11:08
> @marissync The `useQuery` hook accepts a `context` option. Just pass in the `defaultContext` exported by react query.
> 
> ```
> import { defaultContext, useQuery } from '@tanstack/react-query';
> 
> useQuery({ context: defaultContext });
> ```

Thank you, @petercpwong!!

**Comment by system32uwu** [comment] 2022-08-09 00:58
Instead of asking for a failing reproduction wouldn't it be easier to provide a working one? I've tried what was suggested above but it's still failing in the production bundle. I'm using exact versions of react and react-query.

**Comment by arlyon** [comment] 2022-09-14 15:39
I can corroborate the issue with next-transpile-modules.

**Comment by luan-hte** [comment] 2022-09-15 13:01
I had the same issue when using react-query with @tanstack/react-query-devtools. I removed react-query and installed @tanstack/react-query and the issue was gone. Basically use both packages from @tanstack.

**Comment by szmarci** [comment] 2022-09-15 13:04
@system32uwu @SoftMemes @TkDodo I had the same issue. In this case for some reason pnpm installed two versions of react query (taken from the lockfile):
```
/@tanstack/react-query/4.3.4:
/@tanstack/react-query/4.3.4_sfoxds7t5ydpegc3knd667wn6m:
```
 The problem went away when I changed `peerDependencies` in all of my libraries that included react-query as a peer dependecies to include react as well, so changing from this:
```
"peerDependencies": {
   "@tanstack/react-query": "^4.3.4"  
}
```
To this:
```
"peerDependencies": {
   "@tanstack/react-query": "^4.3.4",
   "react": "^17.0.2",
   "react-dom": "^17.0.2"
}
```
And after a `pnpm install`, only one version is installed:

` /@tanstack/react-query/4.3.4_sfoxds7t5ydpegc3knd667wn6m:`

**Comment by jrea** [comment] 2022-10-12 16:51
in a monorepo, using a lib within the repo. I'm using `yarn` workspaces. 

I added the lib as a peer dep, and added a webpack resolver in `next.config.js` like this:

```typescript
  if (options.isServer) {
      config.externals = ['@tanstack/react-query', ...config.externals];
    }

    const reactQuery = path.resolve(require.resolve('@tanstack/react-query'));

    config.resolve.alias['@tanstack/react-query'] = reactQuery;
```

**Comment by ecyrbe** [comment] 2022-10-19 17:45
@TkDodo do you think the issue i linked above can come from esm support ? only one instance of `@tanstack/react-query` is installed, zodios is declaring dependencies as peer dependencies for both react-query and react. 
i checked installed packages, no duplicate.  
seems related to webpack resolution, webpack seems to create two instance duplicate instances of `react-query` in final build.

**Comment by ecyrbe** [comment] 2022-10-19 17:54
@TkDodo do you want me to open a new issue for this ?

**Comment by ecyrbe** [comment] 2022-10-19 19:13
@TkDodo i confirm the bug appeared in `@tanstack/react-query` v4.3.0 and everything was fine on v4.3.2
I'll create an issue since i now have reproductible test case

**Comment by rametta** [comment] 2022-11-10 20:13
@ecyrbe Do you have a link to the issue you created? I am also experiencing this issue

**Comment by ecyrbe** [comment] 2022-11-10 21:05
@rametta here : https://github.com/TanStack/query/issues/4346

But i closed it since i found that the issue is not in tanstack query but in webpack+next . The only way to make it go away is for your library to export esm + cjs packages

**Comment by rametta** [comment] 2022-11-10 21:08
Interesting, I also made a reproduction repo https://github.com/rametta/react-query-v4-bug-repro but it's not using Next, it's using Vite. I will try to export both esm and cjs in my package, thank you

**Comment by rametta** [comment] 2022-11-10 21:41
Yup confirmed it works now with ESM, I need to add these options to my typescript tsc compilation command `--moduleResolution node --target es2015 --esModuleInterop` and defined both in my package.json, cjs in the main field and esm in the module field

**Comment by rametta** [comment] 2022-11-10 22:43
@ecyrbe Actually I'm still having the issue with NextJS even though I'm building the ESM now. Vite is fixed, but NextJS is still throwing the same error. Any idea why? Anything special I need to define in NextJS?

**Comment by ecyrbe** [comment] 2022-11-10 22:48
@rametta  Your package.json need to declare `exports`.
Take a look at how i do it here: https://github.com/ecyrbe/zodios/blob/main/package.json

**Comment by rametta** [comment] 2022-11-11 13:55
@ecyrbe That doesn't seem to help unfortunately. I got something semi working by specify `"type": "module"` in my package.json and importing directly from the esm dir in my code, but I wish it was more automatic

**Comment by ecyrbe** [comment] 2022-11-11 14:06
There is an ugly workaround for next if all other things don't work (idea from @jrea ) : https://github.com/ecyrbe/zodios-express/blob/a237332b38cf0d8edb49edafb66c2d659a1d35f5/examples/next/next.config.js

**Comment by rametta** [comment] 2022-11-11 14:11
Actually your previous comment did work, I just realized I needed to delete the Next cache (`.next` dir) before rebuilding because I was still getting the old package.json 🤦 
What a rollercoaster 😄 Thanks again

**Comment by tonyYo00** [comment] 2022-11-24 03:27
> @ecyrbe That doesn't seem to help unfortunately. I got something semi working by specify `"type": "module"` in my package.json and importing directly from the esm dir in my code, but I wish it was more automatic

Great

**Comment by Darkhorse-Fraternity** [comment] 2022-11-24 06:07
@rametta It is just useful in localhost. It fails when running in git action or docker. See here: https://github.com/Darkhorse-Fraternity/monad-stack/actions/runs/3537468733

**Comment by rametta** [comment] 2022-11-24 12:34
The solution that worked for me also worked in GitHub actions with a nextjs prod build consuming the package

**Comment by adairrr** [comment] 2022-12-03 20:49
I was able to reproduce the issue, which seems to be something with yarn v3 dependency resolution here: 
https://github.com/adairrr/missing-query-provider-repro

**Comment by emurano** [comment] 2022-12-09 05:48
https://github.com/vitejs/vite/issues/6780#issuecomment-1059677499

Make sure your library has **all** peer dependencies listed in your rollup config in your vite config file: build.rollupOptions.external

**Comment by johnayoung** [comment] 2022-12-14 15:27
Just want to add here that I also had this problem with my tsconfig.json. Removing additional "lib" declarations solved it for me:

**Previous**
`{
  "compilerOptions": {
    "target": "ES5",
    "lib": ["ES2017", "ES7", "ES6", "dom"]
  },
}
`

**New**
`{
  "compilerOptions": {
    "target": "ES5"
  },
}
`

**Comment by nctay** [comment] 2022-12-15 19:26
> in a monorepo, using a lib within the repo. I'm using `yarn` workspaces.
> 
> I added the lib as a peer dep, and added a webpack resolver in `next.config.js` like this:
> 
> ```ts
>   if (options.isServer) {
>       config.externals = ['@tanstack/react-query', ...config.externals];
>     }
> 
>     const reactQuery = path.resolve(require.resolve('@tanstack/react-query'));
> 
>     config.resolve.alias['@tanstack/react-query'] = reactQuery;
> ```

React-query V4 update:
```ts
webpack: (config, options) => {
      if (options.isServer) {
        config.externals = ['@tanstack/react-query', ...config.externals]
      }
      config.resolve.alias['@tanstack/react-query'] = path.resolve(
        require.resolve('@tanstack/react-query'),
        '../../../'
      )
      return config
    }
```

**Comment by emurano** [comment] 2023-02-06 23:02
> I don't want people to have to install `react-query` in their own project just to use my package.

Then you need to provide react-query as a dependency instead of a peer dependency. Peer dependencies are a declaration that the module using your module *must* have the dependency installed in order to use your module.

**Comment by rwieruch** [comment] 2023-02-13 21:13
Just for the purpose of documenting it somewhere: We got the `Error: No QueryClient set, use QueryClientProvider to set one` in a project too -- which happened because we had [two react-query installations](https://github.com/TanStack/query/issues/3707).

The setup with the problem:

```
- app/
--- package.json <- react-query installation
--- shared-library/
------ docs/
--------- package.json <- react-query installation
------ packages/
--------- a/
------------ package.json
--------- b/
------------ package.json
--------- c/
------------ package.json
```

The architecture used a git submodule to nest a shared library into various applications. Because of this issue here, we restructured the whole architecture to a monorepo structure to have the react-query installations not nested but side by side instead.

The new setup without the problem:

``
- shared-library/ <- monorepo
--- app/
------ package.json <- react-query installation
--- docs/
------ package.json <- react-query installation
--- packages/
------ a/
--------- package.json
------ b/
--------- package.json
------ c/
--------- package.json
```

**Comment by bombillazo** [comment] 2023-04-12 01:45
>
> React-query V4 update:
> 
> ```ts
> webpack: (config, options) => {
>       if (options.isServer) {
>         config.externals = ['@tanstack/react-query', ...config.externals]
>       }
>       config.resolve.alias['@tanstack/react-query'] = path.resolve(
>         require.resolve('@tanstack/react-query'),
>         '../../../'
>       )
>       return config
>     }
> ```

This worked for us! But since our `next.config.js` is at the root, we didn't have to add the path traversing.

**Comment by bertyhell** [comment] 2023-04-24 22:19
Mine worked like this, so you don't have to guess how many levels up you have to go if the nextjs is the root:
```
		// Fix issues with react-query:
		if (options.isServer) {
			config.externals = ['@tanstack/react-query', ...config.externals];
		}
		config.resolve.alias['@tanstack/react-query'] = path.resolve(
			'./node_modules/@tanstack/react-query'
		);
```

**Comment by donalnofrixion** [comment] 2023-07-22 10:35
For anyone else having this problem when using Vite. 

You need to add @tanstack/react-query to the vite.config.ts rollupOptions

`rollupOptions: {
      external: ['react', 'react-dom', 'axios', '@tanstack/react-query'],`

**Comment by lvauvillier** [comment] 2023-07-23 20:14
Interesting, i have another the same issue and all my react-query versions are exactly the same. I have only one react-query version for all my project in my pnpm lockfile.

I `console.log()` the imported useQuery from my main project and from my library and i get:

```javascript
useQuery(arg1, arg2, arg3) {
  const parsedOptions = parseQueryArgs(arg1, arg2, arg3);
  return useBaseQuery(parsedOptions, QueryObserver);
}
```
```javascript
useQuery(arg1, arg2, arg3) {
    const parsedOptions = queryCore.parseQueryArgs(arg1, arg2, arg3);
    return useBaseQuery.useBaseQuery(parsedOptions, queryCore.QueryObserver);
}

```

So, this is the same library version, but one is from useQuery.js file and the other is from useQuery.esm.js file.

I'm trying to figure out how to properly configure it, but having a unique version of react-query don't solve the issue in all cases!

**Comment by tqhoughton** [comment] 2024-01-31 01:30
> > I appreciate that this isn't much to go on, but in general, what is the recommended method for providing custom hooks based on react-query in a library in terms of dependencies and configuration of the query client?
> 
> if you want a shared scope, meaning that the library uses the same context / client as the application that includes it, I would do it like you've described (I think):
> 
> * have the `lib` define `react-query` as `peerDependency`
> * have the `app` create the `queryClient` and the `QueryClientProvider`.
> 
> the `useQuery` calls in the lib _should_ just pick up that client. If that's not the case, you likely have either two versions of react-query or two versions of react around.
> 
> if you want an isolated scope, I would take a look at the [custom context feature for v4](https://react-query-beta.tanstack.com/guides/migrating-to-react-query-4#custom-contexts-for-multiple-providers).

We have this exact setup and are still running into this `No QueryClient set, use QueryClientProvider to set one` issue with react-query v4. Figured that as long as the app that imports the component is wrapped in a QueryClientProvider it would be fine as you said but somehow it doesn't seem to be finding the right version of react-query from the lib component even though it has react-query and react as a peer dependency. Confirmed that there is only 1 version of `@tanstack/react-query` in the yarn.lock file in the app repo.

Is converting our lib component to export as an ESM module really the only option we have to fix this?

**Comment by adrianzielonka** [comment] 2024-05-10 08:46
> > > I appreciate that this isn't much to go on, but in general, what is the recommended method for providing custom hooks based on react-query in a library in terms of dependencies and configuration of the query client?
> > 
> > 
> > if you want a shared scope, meaning that the library uses the same context / client as the application that includes it, I would do it like you've described (I think):
> > 
> > * have the `lib` define `react-query` as `peerDependency`
> > * have the `app` create the `queryClient` and the `QueryClientProvider`.
> > 
> > the `useQuery` calls in the lib _should_ just pick up that client. If that's not the case, you likely have either two versions of react-query or two versions of react around.
> > if you want an isolated scope, I would take a look at the [custom context feature for v4](https://react-query-beta.tanstack.com/guides/migrating-to-react-query-4#custom-contexts-for-multiple-providers).
> 
> We have this exact setup and are still running into this `No QueryClient set, use QueryClientProvider to set one` issue with react-query v4. Figured that as long as the app that imports the component is wrapped in a QueryClientProvider it would be fine as you said but somehow it doesn't seem to be finding the right version of react-query from the lib component even though it has react-query and react as a peer dependency. Confirmed that there is only 1 version of `@tanstack/react-query` in the yarn.lock file in the app repo.
> 
> Is converting our lib component to export as an ESM module really the only option we have to fix this?

See @donalnofrixion's answer above, it should solve your issue.

**Comment by austinlangdon** [comment] 2024-05-21 15:15
Both our next.js (webpack) app and react (vite) app faced this issue within our monorepo.

Here were the solutions for both


**Vite:** add a resolve alias to `vite.config.ts`
```typescript
resolve: {
  alias: {
    '@tanstack/react-query': path.resolve(__dirname, './node_modules/@tanstack/react-query')
  }
}
```

**Next.js:** add a resolve alias to `next.config.ts`

```typescript
webpack: (config, { isServer }) => {
    if (isServer) {
      config.externals = ['@tanstack/react-query', ...config.externals];
    }
    config.resolve.alias['@tanstack/react-query'] = path.resolve(
      './node_modules/@tanstack/react-query'
    );

    return config;
  },
```

**Comment by pycanis** [comment] 2024-07-18 17:48
I think I've tried everything from this long thread but nothing's working in my case. I'm using [Astro](https://astro.build/) that uses Vite under the hood. I've built a `@lofik/react` library that uses `"@tanstack/react-query": "^5.51.9"`. That's the only place where this dependency is specified.

`npm list @tanstack/react-query`
```
my-app@0.0.1
└─┬ @lofik/react@1.0.23
  └── @tanstack/react-query@5.51.9
```

`@lofik/react` defines `QueryClientProvider` with `QueryClient` in a standard way. Then it exports some hooks that make use of `useQuery` (`useLofikQuery`) and `useMutation` (`useLofikMutation`).

`DashboardLayout.astro`
```
    <LofikProvider client:only="react" transition:persist>
      <slot />
    </LofikProvider>
```

Always getting `No QueryClient set, use QueryClientProvider to set one` I attempt to use `useLofikQuery`. I've been banging my head on this for days, any help appreciated.

**Comment by pycanis** [comment] 2024-07-19 04:57
Here's a reproducible example to the above:

https://stackblitz.com/edit/github-njjsdv

**Comment by navignaw** [comment] 2024-07-26 20:06
Any thoughts on adding a better error message when this happens? Given the length of this thread it's clear that hundreds of developer hours have been lost debugging this. Here's a pass at a better message:

```
No QueryClient found. There are a few symptoms that can cause this:
- You are missing a QueryClientProvider at the root level of your app which specifies the queryClient: https://tanstack.com/query/latest/docs/framework/react/reference/QueryClientProvider
- You have multiple versions of `@tanstack/react-query` installed in `node_modules`. This is typically the case in monorepos (like pnpm or yarn workspaces) and can be checked with `npm list @tanstack/react-query` or `yarn why @tanstack/react-query`, or by inspecting your `node_modules` directories manually. To fix this...
```

I'm happy to make a PR/change into the [code itself](https://github.com/TanStack/query/blob/ec8e800c66ebdeaf540839021f76d8ffc5ca2711/packages/react-query/src/QueryClientProvider.tsx#L18) but my main blocker is what to put as the resolution suggestion 😅 There are numerous workarounds in this thread but it's not clear to me which is the "blessed" solution.

**Comment by tqhoughton** [comment] 2024-08-18 20:10
> See @donalnofrixion's answer above, it should solve your issue.

Checking back in on this thread, I ended up converting the exporting package to use ESM module exports instead of commonjs and that appears to have fixed it. The info on how to do this in vite was not relevant to me since this was just a standard npm package export/import I was doing. +1 for having better docs that explain what you may be running into when your query client provider and your component that consumes useQuery are not colocated.
