### ISSUE TITLE
react-query-devtools is not working in nextjs v13

### ISSUE THREAD

**Issue by SeungYn** [TanStack/query#5671] opened 2023-07-04 04:35 UTC
### Describe the bug

react-query-devtools is not working in nextjs v13
i'm useing nextjs v13.4.5
"@tanstack/react-query": "^5.0.0-alpha.71",
"@tanstack/react-query-devtools": "^5.0.0-alpha.72",

but error occurs as follows "Attempted import error: 'template is not exported from 'solid-js/web' (imported as 'template')"

and It works fine without devtools

code
```
'use client';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactNode } from 'react';

export default function ReactQueryContext({
  children,
}: {
  children: ReactNode;
}) {
  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      {children}
      <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
  );
}

```

library
<img width="557" alt="image" src="https://github.com/TanStack/query/assets/66045666/b2948959-b452-4333-b3d3-ce647d1a463b">

result
<img width="600" alt="image" src="https://github.com/TanStack/query/assets/66045666/f543b206-4f42-418e-84b5-ea98052bea7b">

### Your minimal, reproducible example

.

### Steps to reproduce

react-query-devtools is not working in nextjs v13
i'm useing nextjs v13.4.5
"@tanstack/react-query": "^5.0.0-alpha.71",
"@tanstack/react-query-devtools": "^5.0.0-alpha.72",

but error occurs as follows "Attempted import error: 'template is not exported from 'solid-js/web' (imported as 'template')"

and It works fine without devtools

### Expected behavior

react-query-devtools is not working in nextjs v13
i'm useing nextjs v13.4.5
"@tanstack/react-query": "^5.0.0-alpha.71",
"@tanstack/react-query-devtools": "^5.0.0-alpha.72",

but error occurs as follows "Attempted import error: 'template is not exported from 'solid-js/web' (imported as 'template')"

and It works fine without devtools

### How often does this bug happen?

None

### Platform

macOs

### Tanstack Query adapter

None

### TanStack Query version

v5.0.0-alpha.71

### TypeScript version

v5.1.3

**Comment by lachlancollins** [comment] 2023-07-06 12:40
Hi @SeungYn , could I ask you to try using the following versions:

```
"@tanstack/react-query": "^5.0.0-alpha.53",
"@tanstack/react-query-devtools": "^5.0.0-alpha.53",
```

**Comment by lachlancollins** [comment] 2023-07-06 17:09
@SeungYn @mcous should be fixed in the next version without needing to install any other dependencies!

**Comment by SeungYn** [comment] 2023-07-10 16:24
thank you!

**Comment by mcous** [comment] 2023-07-11 17:03
@lachlancollins I have upgraded `@tanstack/svelte-query` and `@tanstack/svelte-query-devtools` to `5.0.0-alpha.78` (latest) and I'm still experiencing the same build issue.

It looks like the fix landed in `@tanstack/query-devtools`, but I don't see a corresponding version bump for that package since the fix landed

**Comment by lachlancollins** [comment] 2023-07-12 06:39
True, it didn't get bumped. I might need to change the publish config, it only looks for changes in src and package.json.

**Comment by TkDodo** [comment] 2023-07-14 11:59
I'm seeing the same in one of our examples. @ardeora can you please have a look?

**Comment by TkDodo** [comment] 2023-07-14 12:15
so in [our nextJs example](https://tanstack.com/query/v5/docs/react/examples/react/nextjs) (pages dir), I'm getting `ReferenceError: document is not defined` coming from the devtools:

```
Server Error
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
template
file:///project/sandbox/node_modules/@tanstack/query-devtools/build/esm/index.mjs (809:13)
```

in our [app directory example](https://tanstack.com/query/v5/docs/react/examples/react/nextjs-suspense-streaming), I'm getting 

```
./node_modules/@tanstack/query-devtools/dist/esm/Devtools-ae26dfd2.js
Attempted import error: 'template' is not exported from 'solid-js/web' (imported as 'template').
```

@ardeora can you have a look at this please? I'd like to move to `beta` next week if possible.

**Comment by lachlancollins** [comment] 2023-07-15 09:22
@TkDodo these issues seem to be because the codesandbox is installing an old version of the devtools package. I've manually bumped them in #5715 which should hopefully fix the problem.

**Comment by lachlancollins** [comment] 2023-07-15 09:36
@mcous a new version of [all devtools packages](https://github.com/lachlancollins/tanstack-query/commit/b4050041a364a9d52e7d0529068d4ed6a4cf061d) is available!

**Closed** 2023-07-15 09:36 UTC
Labels: bug, package: react-query-devtools, v5, package: query-devtools

**Comment by yasseralsaidi** [comment] 2023-09-20 09:06
ANY BETA HERE FOR REACT?

**Comment by JohnGemstone** [comment] 2023-10-11 18:45
Same with `alpha.91`

**Comment by TkDodo** [comment] 2023-10-11 18:50
please show a reproduction, we're in `rc.10` already

**Comment by JohnGemstone** [comment] 2023-10-11 20:12
Thanks @TkDodo I created a repo and it worked fine. My issue was where I was wrapping the context in my app..

error layout

```tsx
// src/app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers> // wrapping whole html
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>
  );
}
```

working layout
```tsx
// src/app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers> // wrapping layout children
      </body>
    </html>
  )
}
```
