### ISSUE TITLE
react-query-devtools mess up with rem

### ISSUE THREAD

**Issue by fallenleavesguy** [TanStack/query#6236] opened 2023-10-25 05:44 UTC
### Describe the bug

font size of my html root is 200px.But dev tool is using rem unit.so mess up.

### Your minimal, reproducible example

dont need example

### Steps to reproduce

1. set font size of html root to 200px

### Expected behavior

beautiful ui

### How often does this bug happen?

None

### Platform

ios and android

### Tanstack Query adapter

react-query

### TanStack Query version

5.1.0

**Comment by DamianOsipiuk** [comment] 2023-10-25 12:44
Duplicate of https://github.com/TanStack/query/issues/6226

**Closed by DamianOsipiuk** 2023-10-25 12:44 UTC
Labels: duplicate
