### ISSUE TITLE
Programmatic invalidation of infinite query cache

### ISSUE THREAD

**Issue by usaszerelem** [TanStack/query#5648] opened 2023-06-29 17:12 UTC
### Describe the bug

Problem: queryClient.invalidateQueries() with or without queryKey parameter does not have any effect on the cache maintained by useInfiniteQuery().

Please see discussion: https://github.com/TanStack/query/discussions/1264

### Your minimal, reproducible example

https://tanstack.com/query/v4/docs/react/examples/react/load-more-infinite-scroll

### Steps to reproduce

1.- Start with the useInfiniteQuery() example: https://tanstack.com/query/v4/docs/react/examples/react/load-more-infinite-scroll

2.- Modify this example so that upon an **application** button click, queryClient.invalidateQueries() is called

### Expected behavior

As a user I expect the React Query cache to be cleared, but instead the cache is not cleared.
This can be reproduced with or without passing a queryKey to invalidate. As an example:

const queryClient = useQueryClient();
queryClient.invalidateQueries({queryKey: ['products']});

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Chrome Version 114.0.5735.198 (Official Build) (arm64)

### Tanstack Query adapter

react-query

### TanStack Query version

"@tanstack/react-query": "^4.29.12",

### TypeScript version

"typescript": "^5.0.2",

### Additional context

Work around is to pass a number to increment as part of queryKey

**Comment by EmekaNkwo** [comment] 2023-07-03 20:01
Is this issue still open? 
If yes, can it be assigned to me

**Comment by miladavarni** [comment] 2023-07-11 06:59
I have the same problem, 
Whether to invalidate the cache or to optimistic updates, for infinite queries is a disaster

**Comment by usaszerelem** [comment] 2023-07-11 11:54
@miladavarni - see my work around here: https://github.com/TanStack/query/discussions/1264

**Comment by TkDodo** [comment] 2023-07-15 07:27
> 2.- Modify this example so that upon an application button click, queryClient.invalidateQueries() is called

wow, you didn't even make the effort to actually fork the example and add the button. Thanks I guess ... sure, I'd like to invest more time in this and do this for you, here it is:

https://codesandbox.io/p/sandbox/bold-leftpad-2l8wm3?embed=1&file=%2Fsrc%2Fpages%2Findex.js%3A64%2C67

> As a user I expect the React Query cache to be cleared, but instead the cache is not cleared.

Then you just expect the wrong thing. `invalidateQueries` doesn't clear the cache. Invalidation means "mark something as invalid". It also refetches active queries. It doesn't remove anything from the screen.

This seems to be the whole problem here and in the lengthy discussion before: You have a different interpretation of the word "invalidate". We have a guide in the docs about what "Query invalidation" means: https://tanstack.com/query/v4/docs/react/guides/query-invalidation

> When a query is invalidated with invalidateQueries, two things happen:

> - It is marked as stale. This stale state overrides any staleTime configurations being used in useQuery or related hooks
> - If the query is currently being rendered via useQuery or related hooks, it will also be refetched in the background

---

I still don't know what you want to happen. Click a button and see a hard loading state again? Then use `queryClient.resetQueries()`:

https://codesandbox.io/p/sandbox/jovial-water-y73vnl?embed=1&file=%2Fsrc%2Fpages%2Findex.js%3A64%2C69

Do you want to remove data from the cache without a refetch? Use `queryClient.removeQueries()`:

https://codesandbox.io/p/sandbox/inspiring-noyce-gv8rl7?embed=1&file=%2Fsrc%2Fpages%2Findex.js%3A64%2C16

And you know, the devtools have buttons for all of these things. I have suggested them before as well:

![Screenshot 2023-07-15 at 09 18 59](https://github.com/TanStack/query/assets/1021430/79ce948d-e746-429d-a4f8-cc8f1373a603)

I get that I come across as grumpy now, and that's likely because I am. I've asked you about a reproduction a bunch of times, you didn't provide one, apart from: "fork the example and make it yourself". Why should I ? It's your problem. You want my help. Yet you don't even do the minimal, required things. You haven't read the docs. You haven't tried out the devtools to see how things behave.

https://tkdodo.eu/blog/how-can-i#2-do-your-homework

**Closed by TkDodo** 2023-07-15 07:27 UTC
