### ISSUE TITLE
useQuery refetch never throw error for object

### ISSUE THREAD

**Issue by whysetiawan** [TanStack/query#5555] opened 2023-06-10 16:46 UTC
### Describe the bug

I was trying to work with lazy query and use `refetch` for trigger the query. Everything was fine until i try to get the error thrown by `queryFn`. Seems like the error from the `refetch` function never change and i also can't catch the error if it's an object.

```

const useFooQuery = () => {
  const queryInfo = useQuery({
    enabled: false,
    queryFn: () => {
      throw {
        error: "TEST ERROR",
      };
    },
    queryKey: ["foo"],
  });

  const handleLazyFetch = async () => {
    try {
      const res = await queryInfo.refetch();
      if (res.isError) {
        // this code isn't work.
        console.log("error result", res.error);
      }
    } catch (error) {
      // i can't catch if the error is object.
      console.log("CATCHED ERROR", error);
    }
  };

  return {
    ...queryInfo,
    handleLazyFetch,
  };
};

```

### Your minimal, reproducible example

the code above 

### Steps to reproduce

try to change the `queryFn` throw with string or object then call the `handleLazyFetch`

### Expected behavior

I expected the returned error result from `refetch` can be accessed whether in catch block or `result.error` property.

### How often does this bug happen?

Every time

### Platform

Platform : React Native
React Version : 16.12.0

### Tanstack Query adapter

None

### TanStack Query version

4.29.12

**Comment by TkDodo** [comment] 2023-06-12 12:47
> Your minimal, reproducible example
the code above

please put that code above into a runnable codesandbox or an open source repo so that I can actually run it.

**Comment by incepter** [comment] 2023-07-03 11:13
If I understand well, he wants that the `refetch` function throws in case of errors.

The refetch function is a void function that actually does the _try_ catch internally, or just schedules a run to be performed later (or no run at all?). Which means that the refetch function is safe to be used everywhere. To get the errored state, you will need to subscribe to the query (not sure how) and react to state changes while targeting the error state.

Why the refetch doesn't throw ? because it will be mostly uncatched and there are a subscribe and getState alternatives.

**Comment by incepter** [comment] 2023-07-03 11:13
I don't know, but maybe "per run" callbacks could be a good idea in such situations.

**Comment by TkDodo** [comment] 2023-07-14 14:32
> If I understand well, he wants that the refetch function throws in case of errors.

If that's the case: you can do that by passing `throwOnError: true` to `refetch`

closing as there is no reproduction

**Closed by TkDodo** 2023-07-14 14:32 UTC
Labels: needs-info
