### ISSUE TITLE
ESLint prefer-query-object-syntax does not catch issues in v4.36.1

### ISSUE THREAD

**Issue by raulpineda** [TanStack/query#6496] opened 2023-12-06 15:29 UTC
### Describe the bug

I configured prefer-query-object-syntax to error to make it easier to upgrade to v5 in the near future, but the eslint rule is not catching obvious errors 

### Your minimal, reproducible example

Minimal example in an [eslint-online-playground](https://eslint-online-playground.netlify.app/#eNqNk01v2zAMhv8KoUtbIE4wbNghQ4cNKIoNO+yr2A5VByg2YyuxJY+SUweG//soqU2TbGsL+GKKfPnyETUIR/kMe9W0NU5XTsyFblpLHgboHH7tkLYwwpJsA1K888o4r/L1jFDlPvsdjqV4I4002Mey3HJGKP1g7fqqUv57Zbu6uFS6hnM4PYPztzvhU2kArqVYqEKKmwnMZvARWAdzD77SDrwFT7oskfgfAV2tjQfqapzAovOg+XNgrA9CSXsYJ+FnADRqUWMxZ4UOIUTPnuHzi3Lub59DkIzDfsLtHK5P7PrkJvaJwUszP+x+0Jsj4+OtAxz3U/vq/YVeLpHQ+G88Y/AxQIEtjE/YUYygQsoCGTYWQHIECGvcKOMnsOq4o6vsrTYlo1SB745nW3elNoHkraU1Z/xjMHbxMAeIiZimYsp5aazhtYmmpEhiTgr2tb8wd6uSqEmBvUdT3KclrTlhbpuG4xj34U5QkUP63HrN2EJ+bBQ18kb9QHJ8EOJS1Mqj81LEypDhbEc5Xm1bTAmNLZiQFOE83ZQUgdmh7pHpWUvIl5KWPbOLFa9n5rbGqz6pIpGlva7H9dhXivnrDWaMMfbaFUUnDJaJtlyhyvAI93kWuLnANjAxuT4ymrD9Z/YHFyktSzdz/2ZDza9X05evpy/2XIx/AMmMYak=)

### Steps to reproduce

install `eslint@8.55.0`
install "@tanstack/eslint-plugin-query@4.36.1"
configure prefer-query-object-syntax as error
write a function that uses useQuery with an unnamed first parameter as a key

### Expected behavior

As a user, I expect `useQuery(['an-unnamed-array-first-parameter'])` to trigger the eslint rule error

### How often does this bug happen?

Every time

### Platform

MacOS
VSCode 1.84.2
ESLint 8.55.0

### Tanstack Query adapter

react-query

### TanStack Query version

4.36.1

**Comment by TkDodo** [comment] 2023-12-12 10:08
seems more like the rule doesn't work at all in this playground?

I just tried out v4.36.1 in one of our repos and it works just fine:

![Screenshot 2023-12-12 at 11 07 14](https://github.com/TanStack/query/assets/1021430/d3b8d371-8b77-4e4c-aff9-272fae9c534d)

so please maybe show a fully configured github repo because I think there's nothing wrong with the lint rule

**Comment by raulpineda** [comment] 2023-12-20 14:39
Apologies about the late reply. Here's the requested repo https://github.com/raulpineda/eslint-query-test

The `prefer-query-object-syntax` rule does not trigger, but `exhaustive-deps` does
![image](https://github.com/TanStack/query/assets/121022/92cb659e-fe44-4d39-a03d-161aae39f42d)

**Comment by TkDodo** [comment] 2023-12-20 15:05
this is so weird. The very same code errors in my project:

![Screenshot 2023-12-20 at 16 03 50](https://github.com/TanStack/query/assets/1021430/7ef9527f-1e61-4d0d-b36a-68c1a7f56164)

![Screenshot 2023-12-20 at 16 03 44](https://github.com/TanStack/query/assets/1021430/c85ca3b0-2801-4b4d-a504-7696fdbb942a)

I'm not really sure how this is possible. @Newbie012 FYI.

@raulpineda please fix the lock file in the reproduction - it contains references to private registries that I couldn't pull from. Had to delete the lock file and re-create it, I think that's a left-over.

**Comment by Newbie012** [comment] 2023-12-20 18:51
It seems like this rule doesn't work properly with ESLint's default parser [Espree](https://eslint.org/docs/latest/use/core-concepts#:~:text=By%20default%2C%20ESLint%20uses%20the,have%20to%20use%20them%20directly).

As a workaround, you could:

1. temporarily `npm install @typescript-eslint/parser`
2. set `parser: "@typescript-eslint/parser",` in your `.eslintrc.js` file 
3. run eslint again.

**Comment by raulpineda** [comment] 2023-12-20 20:59
The lock file has been recreated. I can confirm that using the typescript eslint parser I see errors as expected. 

The rule was indeed deleted in 5.0.0, since the object syntax is the only valid one

**Comment by TkDodo** [comment] 2023-12-21 08:23
okay, then I'll once again close this issue because there is a workaround, and we likely won't invest more into a rule that is already deleted in the latest version.

**Closed by TkDodo** 2023-12-21 08:23 UTC
Labels: bug, package: eslint-plugin-query
