### ISSUE TITLE
[Vue]: skipToken example is misleading

### ISSUE THREAD

**Issue by SomaH123** [TanStack/query#7371] opened 2024-05-03 13:18 UTC
### Describe the bug

The skipToken documentation suggests to me that `skipToken` can be used similarly to `enabled`, but `enabled` can actually be reactive, so if something changes there, the query can actually be turned on/off, but in the case of `skipToken`, the value is evaluated on creation, and that doesn't change anymore, even if the ternary operator uses reactive values in there.

The example also has an unused `isEnabled` computed, and it relies on the `filter`, instead of `filter.value` in the ternary operator, which will always evaluate to true, thanks to it being a Ref object.

The skipToken solution in its current shape is not usable for use-cases where on component mounting one of the params is empty for example (like on a search page), and the moment somebody enters a search term, the query should be enabled.

### Your minimal, reproducible example

https://tanstack.com/query/v5/docs/framework/vue/guides/disabling-queries

### Steps to reproduce

1. Use the example code
3. See that the fetchTodos is called even if the filter has no actual value

1. Use the example code
2. Change the ternary operator to rely on the value of the filter
3. Set the filter value after mounting happened
4. See that the fetchTodos is not called

### Expected behavior

I'd expect the documentation to make these caveats clearer, or preferably make the skipToken solution reactive somehow.

### How often does this bug happen?

Every time

### Platform

Probably all of them

### Tanstack Query adapter

vue-query

### TanStack Query version

5.29.0

### TypeScript version

5.4.5

**Comment by DamianOsipiuk** [comment] 2024-06-26 22:16
Fixed in docs

**Closed by DamianOsipiuk** 2024-06-26 22:16 UTC

**Comment by SomaH123** [comment] 2024-08-28 10:50
Sorry to necro this @DamianOsipiuk, only now I had the opportunity to check the improved docs out. While the proposed solution does seem to work, it causes TypeScript issues. queryFn does not accept ComputedRef as a possible value. Should I create a new issue for this?

**Comment by yakobe** [comment] 2024-09-03 17:14
I'm also having some issues with `skipToken` and cannot seem to get it to work and satisfy typescript.

**Comment by DamianOsipiuk** [comment] 2024-09-03 20:30
> Sorry to necro this [@DamianOsipiuk](https://github.com/DamianOsipiuk), only now I had the opportunity to check the improved docs out. While the proposed solution does seem to work, it causes TypeScript issues. queryFn does not accept ComputedRef as a possible value. Should I create a new issue for this?

Seems to work fine for me, make sure `computed` returns a function or `skipToken`.
Also make sure you are on a latest version.
If it's still a problem, open a new issue with reproduction is TS playground.

```ts
const filter = ref('')
const queryFn = computed(() =>
  filter.value ? () => Promise.resolve(1) : skipToken,
)
```

**Comment by yakobe** [comment] 2024-09-04 17:58
Thanks for the reply @DamianOsipiuk!

It looks like the issue isn't with tanstack query itself but with https://github.com/lukemorales/query-key-factory. It seems that when a `queryFn` is a `computed` in `createQueryKeys` then the `data` is infered as `Ref<unknown>`.  

```ts
// data is inferred as `Ref<unknown>`
const { data } = useQuery(queries.user.single(userId))
```

If i dont use a `computed` with `skipToken` in `createQueryKeys`, but wrap it like this it works fine:

```ts
// data is inferred as `Ref<User>`
const { data } = useQuery({
  ...queries.user.single(userId),
  queryFn: computed(() => (userId.value ? queries.units.single(userId).queryFn : skipToken)),
})
```

Sorry for the confusion. I will see if i can work out a way to describe it as an issue on the query-key-factory repository

**Comment by SomaH123** [comment] 2024-09-06 10:24
Seems like it's not a problem on the latest version anymore, thanks!

**Comment by yakobe** [comment] 2024-10-09 19:02
This looks like the issue on the query key factory in case anyone lands here in the future: https://github.com/lukemorales/query-key-factory/issues/100
