### ISSUE TITLE
`yarn add @tanstack/react-query` responds with 404

### ISSUE THREAD

**Issue by bstro** [TanStack/query#3790] opened 2022-07-08 23:36 UTC
### Describe the bug

Running `yarn add @tanstack/react-query` per docs yields a 404 error.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/627290/178082137-39fb5a52-0ad3-49c0-914b-113371318558.png">

### Your minimal, reproducible example

n/a

### Steps to reproduce

`yarn add @tanstack/react-query`

### Expected behavior

Should work

### Platform

n/a

### react-query version

n/a

**Comment by insuusvenerati** [comment] 2022-07-08 23:45
You can install v4 using `yarn add react-query@beta` for now.

**Comment by Kayyow** [comment] 2022-07-09 15:08
Maybe we should update the [installation docs](https://tanstack.com/query/v4/docs/installation) because it state that you can install the package via `@tanstack/react-query` which isn't currently working.

**Comment by addy** [comment] 2022-07-09 18:30
FWIW this is also occurring for the `npm i @tanstack/react-query` version of the installation process.

**Comment by SeanCassiere** [comment] 2022-07-11 09:46
Hey, by any chance is there something going on with the package being only accessible via an Org or something?

It is currently not listed on NPM or the Yarn registry.
[NPM @tanstack/react-query](https://www.npmjs.com/package/@tanstack/react-query) - resolves to a login page
[Yarn @tanstack/react-query](https://registry.yarnpkg.com/@tanstack/react-query) - returns a not found

**Comment by TkDodo** [comment] 2022-07-11 09:50
It hasn't been released on npm yet, the docs redirect was a mistake. Please be patient and use this in the meantime:
https://github.com/TanStack/query/issues/3790#issuecomment-1179431860

**Comment by Dev-eloperr** [comment] 2022-07-15 10:30
I am currently on "react-query": "^4.0.0-beta.23" which I installed using 
`npm i react-query@beta
`
Now, I am facing this issue while installing devtools
1) Running the command in v4 docs (npm i @tanstack/react-query-devtools)
![image](https://user-images.githubusercontent.com/27141130/179206049-5b618e5d-c051-4db4-aabe-fe1865499154.png)

2) Running the same command after removing @tanstack (npm i --save react-query-devtools)
![image](https://user-images.githubusercontent.com/27141130/179206194-8b60f46d-07b9-49da-99aa-02e8e8bf42a8.png)

**Comment by TkDodo** [comment] 2022-07-15 12:12
I know this is really confusing, so let me try to clear it up:

for now, all you need is `npm i react-query@beta` if you want v4 or `npm i react-query` if you want v3.

Both of them work the same way:

```
import { useQuery } from 'react-query'
import { ReactQueryDevTools } from 'react-query/devtools'
```

devtools are bundled with the lib!

---

once we rollout tanstack query, it will be:

```
npm i @tanstack/react-query
npm i @tanstack/react-query-devtools
```

two separate packages, imported separately:

```
import { useQuery } from '@tanstack/react-query'
import { ReactQueryDevTools } from '@tanstack/react-query-devtools'
```

there will be a codemod that automatically transforms all imports.

**Comment by TkDodo** [comment] 2022-07-15 12:58
here's a working sandbox: https://codesandbox.io/s/boring-thunder-gpw4l9?file=/src/index.js

**Comment by billyyyyy3320** [comment] 2022-07-18 09:58
IMHO, the problem is the document of pre-release and latest version are misplaced.

I could see https://tanstack.com/query/v4 in description and readme. Also, what I need for the latest version is mentioned as beta version(?). The content of `https://react-query-beta.tanstack.com/` is for v3, right?
> Still on React Query v2? No problem! Check out the v2 docs here: https://react-query-v2.tanstack.com/.
Would you like to try React Query v4beta? Check out the v4 beta docs here: https://react-query-beta.tanstack.com/.

**Comment by lindan4** [comment] 2022-07-18 18:58
Is there any date on which stable version 4 will be released? The documentation for version 3 was removed or is not available either.

**Comment by TkDodo** [comment] 2022-07-18 19:18
https://github.com/TanStack/query/releases/tag/v4.0.0

**Closed by TkDodo** 2022-07-18 19:18 UTC
