### ISSUE TITLE
V4 Not Working on PReact

### ISSUE THREAD

**Issue by rajeshdish** [TanStack/query#3966] opened 2022-08-01 11:48 UTC
### Describe the bug

As i said in the title, 

React + V4 React Query (Working) | https://codesandbox.io/s/cranky-drake-yg06hx?file=/src/provider.js
PReact + V4 React Query (Not Working) | https://codesandbox.io/s/competent-platform-50c1xz?file=/src/provider.js

But V3 React Query works with PReact

In Above codesandbox i was trying to run simple useMutation with a promise method 

### Your minimal, reproducible example

https://codesandbox.io/s/cranky-drake-yg06hx?file=/src/provider.js

### Steps to reproduce

Shared the codesandbox demo

### Expected behavior

I was expecting data update

### Platform

Windows
NextJs
With Preact

### react-query version

v4.0.10

### TypeScript version

V4.7.4

**Comment by TkDodo** [comment] 2022-08-12 13:57
I can confirm that the mutation is running, it is resolving and data is put into the cache. You can see that here in the log statements and if you click the button after the mutation is finished, the mutationCache is logged.

https://codesandbox.io/s/relaxed-wilson-ntzbtt?file=/src/provider.js

So it must be something on the react hooks layer. In v4, we are using `useSyncExternalStore`, and we're using the `useSyncExternalStore/shim` package from react itself for backwards compatibility with React17.

---

I've debugged this some more and it turns out that `unsubscribe` is called while the mutation is still running, so when it comes back, there is no observer anymore. If you reduce your `setTimeout` from 1 second to 1ms, it seems to work.

The `unsubscribe` is not something that react-query calls, but it's called from react / preact itself when the component unmounts. It's basically the cleanup function from useEffect / useSyncExternalStore. So I guess for some reason, preact thinks that our component unmounts maybe?

**Comment by filoozom** [comment] 2022-08-16 10:27
I think this was actually just fixed in `preact` `v10.10.3` (https://github.com/preactjs/preact/commit/b9f6446e9289591fed05b092aa51a6c74a733702): https://codesandbox.io/s/blissful-currying-xkykle?file=/src/provider.js

**Comment by TkDodo** [comment] 2022-08-16 11:07
nice 👍

**Closed by TkDodo** 2022-08-16 11:07 UTC
