### ISSUE TITLE
[vue] onSuccess hooks much slower than watchers

### ISSUE THREAD

**Issue by marekvanicek** [TanStack/query#4780] opened 2023-01-09 13:19 UTC
### Describe the bug

Big delay of triggering the onSuccess hook after status variable reaches 'success'.

### Your minimal, reproducible example

https://codesandbox

### Steps to reproduce

```ts
function getPersonalData(): Promise<Person> {
    return new Promise((resolve) => {
        resolve({name: 'Jane Doe', phoneNumber: '+420 728 193 052'})
    })
}

const name = ref<string>()
const phoneNum = ref<string>()

const {data: personalData, status} = useQuery(['personalData'], getPersonalData, {onSuccess: () => {
    name.value = personalData.value?.name
    phoneNum.value = personalData.value?.phoneNumber
}})

//watch(status, (newValue) => {
//    if (status.value === 'success') {
//        name.value = personalData.value?.name
//        phoneNum.value = personalData.value?.phoneNumber
//    }
//})
````
First run this the way it is. Then comment the onSuccess hook an uncomment the watcher. The watcher triggers immediately after the status value reaches 'success'. Cant say the same about the onSuccess hook.

### Expected behavior

Imo there should not be any delay and actions should happen immediately after. Watcher shows that its possible.

### How often does this bug happen?

Every time

### Platform

macOS
chrome 105.0.5195.102

### TanStack Query version

4.17.0

### TypeScript version

4.9.3

**Comment by judicaelandria** [comment] 2023-01-09 14:16
Hey! the codesandbox link is not right!

**Comment by DamianOsipiuk** [comment] 2023-01-11 12:52
@marekvanicek Please provide a reproduction example. Ideally with time measurement difference.

Also please keep in mind, that running the same query the second time serves the result from the cache instead of going trough `loading` state. It might not be relevant, but it is something to keep in mind.

**Comment by TkDodo** [comment] 2023-02-14 07:39
closing this because it doesn't have a reproduction. Feel free to reopen once you have one.

**Closed by TkDodo** 2023-02-14 07:39 UTC
Labels: needs-info, package: vue-query
