### ISSUE TITLE
Option useErrorBoundary does not work in vue-query

### ISSUE THREAD

**Issue by hakastein** [TanStack/query#5711] opened 2023-07-14 11:48 UTC
### Describe the bug

Regardless of whether the option useErrorBoundary is specified or not - the behavior of useQuery does not change

### Your minimal, reproducible example

https://codesandbox.io/p/github/hakastein/tanstack-reproduce-bug/master
### Steps to reproduce

1. Create simple app
2. Use useQuery with useErrorBoundary true/false
```vue
<script setup>
import {useQuery} from "@tanstack/vue-query";

const { data, error, isError} = useQuery({
  queryKey: ['test'],
  queryFn: () => {
    throw new Error('tanstack error');
    return 'query data';
  },
  useErrorBoundary: true,
})
</script>

<template>
  <div>
    {{data}}
    {{error}}
  </div>
</template>

<style scoped>

</style>
```
3. See nothing changes

### Expected behavior

Error must be thrown to vue error handler, but it doesn't happen

### How often does this bug happen?

Every time

### Platform

every platform

### Tanstack Query adapter

None

### TanStack Query version

4.29.20

**Comment by DamianOsipiuk** [comment] 2023-07-17 05:44
Duplicate of https://github.com/TanStack/query/issues/5462

**Closed by DamianOsipiuk** 2023-07-17 05:44 UTC
