### ISSUE TITLE
Prefetch in Solid-Start does not hydrate to the client and instead calls the query again

### ISSUE THREAD

**Issue by apatrida** [TanStack/query#6326] opened 2023-11-07 15:12 UTC
### Describe the bug

Taking this sample from Aryan, and changing it to prefect:

https://github.com/apatrida/solid-start-query-streaming-ssr/commit/0218c86e098f0569bb461147ed046f76d1537076

you would expect each query to run 1 time, but instead it runs on server then again on the client.

You can see this in the output from the server log:

```
GET http://localhost:3000/product/1
fetch product 1
fetch sizes 1
fetch recommended 1
fetch reviews 1
PREFETCH product 1 DONE
POST http://localhost:3000/_m/src/routes/product/[id].tsx/0/getProduct 
fetch product 1
POST http://localhost:3000/_m/src/routes/product/[id].tsx/3/getAvailableSizes
fetch sizes 1
POST http://localhost:3000/_m/src/routes/product/[id].tsx/1/getRecommendedPicks
fetch recommended 1
POST http://localhost:3000/_m/src/routes/product/[id].tsx/2/getReviews
fetch reviews 1
PREFETCH reviews  1 DONE
PREFETCH sizes 1 DONE
PREFETCH recommended 1 DONE
```

So the prefetches started, then client calls came in for the same queries, and then the prefetches resolved but the queries were run twice.

### Your minimal, reproducible example

see sample github

### Steps to reproduce

see sample

### Expected behavior

queries to run only once, on the server

### How often does this bug happen?

Every time

### Platform

solid-start

### Tanstack Query adapter

solid-query

### TanStack Query version

5.4.3

### TypeScript version

4.9.5

### Additional context

I updated versions to 6.7.2 and still occurs.

**Comment by ardeora** [comment] 2023-11-08 02:39
Hello! Apologies for the late reply. But, this works as designed. 

In SolidStart, All the components run twice. Once on the server and then on the client. Elements inside JSX, if rendered on the server are not re-created on the client but hydrated. Everything else just runs twice, since it's plain JS. That is the reason why you see prefetchQuery run twice once on the server and then on the client. 

There is another exception to this rule and they are SolidJS [resources](https://docs.solidjs.com/references/api-reference/basic-reactivity/createResource). Resources can run on the server, and if the data from the fetcher is resolved on the server then they can be picked back up on client without having to run the fetcher function again. Solid Query internally implements resources with `createQuery` and `createInfiniteQuery`.

Any queries you create using `createQuery`/`createInfiniteQuery` are run on the server and then if they resolve they are hydrated on the client. This totally eliminates the need of performing a `prefetchQuery`. You can simply write the app like how you would write a client rendered app and get the benefits of a server rendered app when using SolidStart! This infact is a feature and not a bug 😅  

Are there any other reasons why you would want `prefetchQuery`? If there are any use cases that apply we can certainly work on adding those functionality. 

Also the  documentation for Solid Query are sparse but I'll try to add more in the coming weeks

**Comment by apatrida** [comment] 2023-11-08 04:16
I didn't think it was the prefetch running twice, although I should wrap it with `IsServer` to make sure it is fetched on the server.   I'll have to check the client logs as well, but will need a new sample with this one having the API go down.

I'm testing cases that a larger app uses where it fetches data in route data so that the fetches start more concurrently then how they would if they were fetched in the component tree (waterfalling as components block on `Show` or other barriers).  Letting them run serially is a lot slower.

So a prefetch will always run the prefetch on server + the query on the client and does not hydrate the cache or the promise.  I would instead need to run the query, and pass it via routeData to the component rendering tree to then have it serialize across the wire. 

Therefore prefetch only really helps to cache things for later use in the same SSR rendering?  But then that goes to waste having client run them again.

I would change to wrap in an `IsServer` call in your sample, but the hosted server API is down, and I can't find a place to get it to run locally.

In my main app, the `IsServer` doesn't prevent anything being called twice.  Pretech only helps on server in its rendering and then basically is ignored and client may query the same things again.

**Comment by apatrida** [comment] 2023-11-08 06:43
Ok, this test case shows the prefetch working and not querying a second time.

this code:

```import { useNavigate, useRouteData, useSearchParams } from '@solidjs/router';
import { isServer } from 'solid-js/web';
import { createQuery, QueryFunctionContext, useQueryClient } from '@tanstack/solid-query';
import { createContext, createEffect, useContext, Show, Suspense } from 'solid-js';
import server$, { createServerData$ } from 'solid-start/server';
import { ErrorBoundary, RouteDataArgs } from 'solid-start';

type QueryOneResult = { message: string };

const queryFunction = server$(async (ctx: QueryFunctionContext): Promise<QueryOneResult> => {
  console.debug('queryOne server call', ctx.queryKey);
  return { message: `${ctx.queryKey}` };
});

const queryOneDataContext = createContext<QueryOneResult>();

export function routeData(args: RouteDataArgs) {
  console.log('routeData', isServer ? 'on server' : 'on client');
  if (isServer) {
    const id = Number(args.location.query.id ?? 0);
    if (id == 0) {
      console.debug('redirect to start');
      args.navigate('/testReactivity?id=1');
      return { message: 'redirect' };
    }
    const queryClient = useQueryClient();
    void queryClient
      .prefetchQuery({
        queryKey: ['queryOne', id],
        queryFn: queryFunction,
        staleTime: 10 * 1000,
      })
      .then(() => {
        console.debug('routeData', isServer ? 'on server' : 'on client', 'PRELOAD COMPLETE');
      });
  }

  return createServerData$(
    ([_, id]) => {
      const queryKey = ['queryTwo', id];
      console.debug('queryTwo server call', queryKey);
      return { message: `${queryKey}` };
    },
    { key: () => ['queryTwo', Number(args.location.query.id ?? 0)], deferStream: true }
  );
}

export default function TestReactivity() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const id = () => Number(searchParams.id ?? 0);

  const queryOne = createQuery(() => ({
    queryKey: ['queryOne', id()],
    queryFn: queryFunction,
    staleTime: 10 * 1000,
    placeholderData: (d) => d,
  }));

  const rd = useRouteData<typeof routeData>()!;

  createEffect(() => {
    console.debug(
      'queryOne state',
      queryOne.isFetching,
      queryOne.status,
      JSON.stringify(queryOne.data)
    );
  });
  createEffect(() => {
    console.debug('queryTwo state', rd.loading, rd.state, JSON.stringify(rd()));
  });

  function gotoNext() {
    console.debug('...goto next');
    let nextId = id() + 1;
    if (nextId === 11) {
      nextId = 1;
    }
    //setSearchParams({id: nextId});
    navigate('/testReactivity?id=' + nextId);
  }

  return (
    <ErrorBoundary>
      <Suspense>
        <div>
          <div>
            Test Reactivity <button onClick={() => gotoNext()}>next</button>
          </div>
          <hr />
          <Show
            when={queryOne.data?.message}
            fallback={<div>waiting on queryOne...</div>}
          >
            <div>{queryOne.data?.message}</div>

            <queryOneDataContext.Provider value={queryOne.data}>
              {/* not reactive */}
              <SubComponent whichQuery={'queryOne'} />
            </queryOneDataContext.Provider>
          </Show>
          <hr />
          <Show
            when={rd()}
            fallback={<div>waiting on queryTwo...</div>}
          >
            <div>{rd()?.message}</div>

            <queryOneDataContext.Provider value={rd()}>
              <SubComponent whichQuery={'queryTwo'} />
            </queryOneDataContext.Provider>
          </Show>
        </div>
      </Suspense>
    </ErrorBoundary>
  );
}

type SubComponentProps = {
  whichQuery: string;
};
function SubComponent(props: SubComponentProps) {
  const data = useContext(queryOneDataContext);
  createEffect(() => {
    console.debug(`sub data`, JSON.stringify(data));
  });
  return <div>sub: {data?.message}</div>;
}

```

outputs on first load on `http://localhost:3000/testReactivity?id=1`, SERVER:

```
GET http://localhost:3000/testReactivity?id=1
routeData on server
queryOne server call [ 'queryOne', 1 ]
queryTwo server call [ 'queryTwo', 1 ]
routeData on server PRELOAD COMPLETE

```

and on CLIENT:

```
routeData on client
testReactivity.tsx:63 queryOne state false success {"message":"queryOne,1"}
testReactivity.tsx:71 queryTwo state false ready {"message":"queryTwo,1"}
testReactivity.tsx:126 sub data {"message":"queryOne,1"}
testReactivity.tsx:126 sub data {"message":"queryTwo,1"}
```

and on the `next` button, SERVER:

```
POST http://localhost:3000/_m/src/routes/testReactivity.tsx/1/routeData
POST http://localhost:3000/_m/src/routes/testReactivity.tsx/0/queryFunction
queryTwo server call [ 'queryTwo', 2 ]
queryOne server call [ 'queryOne', 2 ]
```

and CLIENT:

```
...goto next
testReactivity.tsx:126 sub data {"message":"queryTwo,2"}
testReactivity.tsx:71 queryTwo state false ready {"message":"queryTwo,2"}
testReactivity.tsx:63 queryOne state true success {"message":"queryOne,1"}
testReactivity.tsx:63 queryOne state false success {"message":"queryOne,2"}
testReactivity.tsx:63 queryOne state true success {"message":"queryOne,2"}
```

is as expected.  if I loop around quickly before the stale timer ends on each the cached queries kick in.

**Comment by apatrida** [comment] 2023-11-08 06:43
This does show that `query.data` is not reactive through a provider while a Resource is reactive through the provider.

**Comment by TkDodo** [comment] 2023-11-28 10:39
@ardeora if this works as designed - can we close the issue ?

**Closed as not planned** 2023-11-28 12:29 UTC
Labels: works as designed

**Comment by huseeiin** [comment] 2025-08-29 15:42
> Hello! Apologies for the late reply. But, this works as designed.
> 
> In SolidStart, All the components run twice. Once on the server and then on the client. Elements inside JSX, if rendered on the server are not re-created on the client but hydrated. Everything else just runs twice, since it's plain JS. That is the reason why you see prefetchQuery run twice once on the server and then on the client.
> 
> There is another exception to this rule and they are SolidJS [resources](https://docs.solidjs.com/references/api-reference/basic-reactivity/createResource). Resources can run on the server, and if the data from the fetcher is resolved on the server then they can be picked back up on client without having to run the fetcher function again. Solid Query internally implements resources with `createQuery` and `createInfiniteQuery`.
> 
> Any queries you create using `createQuery`/`createInfiniteQuery` are run on the server and then if they resolve they are hydrated on the client. This totally eliminates the need of performing a `prefetchQuery`. You can simply write the app like how you would write a client rendered app and get the benefits of a server rendered app when using SolidStart! This infact is a feature and not a bug 😅
> 
> Are there any other reasons why you would want `prefetchQuery`? If there are any use cases that apply we can certainly work on adding those functionality.
> 
> Also the documentation for Solid Query are sparse but I'll try to add more in the coming weeks

how do we preload on hover?
