### ISSUE TITLE
Infinite Queries Repeat request

### ISSUE THREAD

**Issue by cfj1996** [TanStack/query#4668] opened 2022-12-21 08:56 UTC
### Describe the bug

Lots of duplicate requests when scrolling too fast

![image](https://user-images.githubusercontent.com/32974530/208860863-695b580e-f659-46c5-8fb1-8717e69ee4d5.png)

### Your minimal, reproducible example

https://codesandbox.io/s/reverent-sanne-witpsy

### Steps to reproduce

Select all the tables with the mouse and scroll down

### Expected behavior

should output pageParam 0,1,2,3,4,5...

### How often does this bug happen?

None

### Platform

win10 
Chrome 108.0.5359.125

### Tanstack Query version

4.16.1

**Comment by rbluena** [comment] 2022-12-21 13:55
@TkDodo I guess what he mean't is to highlight the content in the table. I guess by highlighting the rows from top to the bottom. But still it seems not to be the case on my end, because I couldn't be able to reproduce the issue. @cfj1996

**Comment by TkDodo** [comment] 2022-12-21 13:57
yeah I also tried "highlighting" as shown in the image, but I couldn't reproduce the issue. Maybe this is where a video would actually help 😅

**Comment by TkDodo** [comment] 2023-01-15 14:27
closing this for now because it's not reproducible and OP hasn't answered again.

**Closed by TkDodo** 2023-01-15 14:27 UTC

**Comment by cfj1996** [comment] 2023-01-16 10:21
> @TkDodo我猜他的意思不是要突出显示表格中的内容。我想通过突出显示从上到下的行。但在我看来情况并非如此，因为我无法重现该问题。@cfj1996

https://www.awesomescreenshot.com/video/14018898?key=003ba633335d05d6fc5e3c1ba4c1482c 
need brute force scrolling
