### ISSUE TITLE
getQueryData suddenly returns undefined for a query even though no update to query data has occurred

### ISSUE THREAD

**Issue by LukasDeco** [TanStack/query#7110] opened 2024-03-14 14:55 UTC
### Describe the bug

In a React component, calling queryClient.getQueryData for a specific query is suddenly returning undefined after previously returning data during subsequent renders, despite no new calls to queryClient.setQueryData for that query. This behavior is observed even when console logging confirms that setQueryData has not been invoked for the affected query, so there is no clear reason why it would turn undefined suddenly.

### Your minimal, reproducible example
https://codesandbox.io/p/sandbox/react-query-bug-qw336y?file=%2Fsrc%2FApp.js

### Steps to reproduce

1. Set up a React component that utilizes getQueryData, and call setQueryData in a different part of the application to populate data in the query.
2. Inside the component, log the result of queryClient.getQueryData('queryKey') to the console during render.
3. Ensure there are no follow up invocations of queryClient.setQueryData for the 'queryKey' that would suddenly set it to undefined.
4. Observe the console log during the component's render phase.

### Expected behavior

As a user, I expected getQueryData to not return some new value unless something happened to update that query. If this is something to do with a cache becoming stale, that is something I didn't see in the docs.

### How often does this bug happen?

Often

### Platform

Browser: Chrome

### Tanstack Query adapter

react-query

### TanStack Query version

5.24.1

### TypeScript version

5.2.2

**Comment by TkDodo** [comment] 2024-03-14 14:59
can't access that sandbox, please make it public

**Comment by frederikhors** [comment] 2024-03-30 21:37
Same problem here @TkDodo unfortunately. In svelte using:

```
@tanstack/eslint-plugin-query": "5.28.6",
"@tanstack/query-persist-client-core": "5.28.9",
"@tanstack/svelte-query": "5.28.9",
"@tanstack/svelte-query-devtools": "5.28.10",
```

I'll try to create a reproduction soon.

**Comment by frederikhors** [comment] 2024-03-30 21:45
@LukasDeco do you have any work-around? Any fix?

**Comment by frederikhors** [comment] 2024-03-30 23:10
I don't know if this is the same issue I'm facing right now. I opened https://github.com/TanStack/query/issues/7204 with a reproduction. @LukasDeco your reproduction is 404.

**Comment by TkDodo** [comment] 2024-04-02 12:29
gonna close this because the reproduction is inaccessible.

**Closed by TkDodo** 2024-04-02 12:29 UTC

**Comment by LukasDeco** [comment] 2024-04-02 17:47
> @LukasDeco do you have any work-around? Any fix?

@frederikhors I just had to add some extra logic to catch if it went undefined and then throw it in a useState. It's a bit of a mess.

**Comment by LukasDeco** [comment] 2024-04-02 17:49
@TkDodo I changed to public

**Comment by LukasDeco** [comment] 2024-04-02 17:54
@TkDodo the example is updated to be working now: https://codesandbox.io/p/sandbox/react-query-bug-qw336y?file=%2Fsrc%2FApp.js%3A14%2C26
