### ISSUE TITLE
TypeScript error in @tanstack/query-core/src/query.ts

### ISSUE THREAD

**Issue by geoffsimp** [TanStack/query#4591] opened 2022-12-03 01:18 UTC
### Describe the bug

In the `createRetryer` config, the `TError` type is implicitly resolved as `TError | { silent?: boolean | undefined }`. The config's `onFail` function call's the Query class's `dispatch` method, where the class's `TError` type is only `TError` (not `TError | { silent?: boolean | undefined }`). Webpack is failing to build due to this error.

### Your minimal, reproducible example

https://github.com/TanStack/query/blob/main/packages/query-core/src/query.ts

### Steps to reproduce

1. Open query-core/src/query.ts in a code editor
2. Compile the TypeScript
3. View the error

### Expected behavior

As a user, I expected no compilation errors but I am seeing a compilation error

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/32892951/205415467-a5145aa2-ff59-4cc1-88ed-be508b20e6b9.png)

### Platform

macOS

### Tanstack Query version

4.19.0

### TypeScript version

4.9.3

**Comment by TkDodo** [comment] 2022-12-03 07:24
please show a runnable reproduction - I'm not seeing this error in our codebase. I've also quickly upgraded TS to 4.9.3 (we're currently on 4.8) but this error doesn't surface in that version either

**Comment by geoffsimp** [comment] 2022-12-03 09:03
Unfortunately I can't provide the project where this error is occurring. I just tried setting up a basic project to demonstrate, but I'm not getting the error either. I've manually gone through the code and verified that an error should be happening, so I'm not sure why it isn't being shown.

A similar example in the same file:
On line 429 inside the `onError` function, the `error` attribute is type casted to `TError`. Removing this type casting results in the same error message that I'm getting on line 477. I believe adding this same type casting to line 477 is the fix for this "bug".
![image](https://user-images.githubusercontent.com/32892951/205433134-b8d81a65-fa46-445d-8caf-71b6f72b424e.png)

**Comment by TkDodo** [comment] 2022-12-03 09:06
> Webpack is failing to build due to this error.

I'm wondering why webpack would be interested in the react-query sources and typescript files? It's a third party lib so it should pick up the transpiled esm or cjs versions ...

given that you cannot reproduce this issue and I also don't see any errors, I'm gonna close this as it's likely something with your specific setup and not an actual bug in react-query.

**Closed by TkDodo** 2022-12-03 09:06 UTC
Labels: types, needs-info

**Comment by charleskoehl** [comment] 2022-12-09 19:01
I have the same issue. I branched my app and deleted almost all of it until I narrowed it down to this:

If I add this line to any file, even without using MutationOptions in the file, I get the error.
```js
import { MutationOptions } from '@tanstack/query-core/src/types'
```

```shell

../../node_modules/@tanstack/query-core/src/query.ts:477:55
Type error: Type 'TError | { silent?: boolean; }' is not assignable to type 'TError'.
  'TError' could be instantiated with an arbitrary type which could be unrelated to 'TError | { silent?: boolean; }'.

  475 |       onError,
  476 |       onFail: (failureCount, error) => {
> 477 |         this.dispatch({ type: 'failed', failureCount, error })
      |                                                       ^
  478 |       },
  479 |       onPause: () => {
  480 |         this.dispatch({ type: 'pause' })
```

**Comment by TkDodo** [comment] 2022-12-09 19:30
> import { MutateOptions } from '@tanstack/query-core/src/types'
// OR
import { MutationOptions } from '@tanstack/query-core/src/types'

You shouldn't import from `/src/` ❗ 

both things are exported properly:

```
import { MutateOptions, MutationOptions } from '@tanstack/react-query'
```

I don't see such an error in our internal code-base...

**Comment by charleskoehl** [comment] 2022-12-09 19:39
Thanks. I just corrected the import path per @TkDodo and it eliminated the error. I don't know why the src directory was suggested the first time I wrote the import line, but I did run yarn upgrade-interactive since then, and did not change the semver: `"@tanstack/react-query": "^4.10.3",`

**Comment by charleskoehl** [comment] 2022-12-09 19:45
@geoffsimp , I didn't need to add `"@tanstack/react-query": ["./node_modules/@tanstack/react-query/build/lib/*"]` to compilerOptions.paths in my tsconfig.

**Comment by geoffsimp** [comment] 2022-12-09 19:46
@charleskoehl That might have been specific to webpack then
