### ISSUE TITLE
SSR & SvelteKit prefetching example doesn't work as expected

### ISSUE THREAD

**Issue by universaltonton** [TanStack/query#5059] opened 2023-03-01 15:33 UTC
### Describe the bug

The docs (https://tanstack.com/query/latest/docs/svelte/ssr#using-prefetchquery) says that when using `prefetchQuery` in `+page.ts`, a refetch won't be triggered when calling `createQuery` in `+page.svelte` (with the same query key of course).

After following the documentation, it seems it doesn't work that way and a refetch does happen.

The example provided in documentation also clearly show this behaviour as shown in the screenshots below (the 3rd "posts" in the 2nd screenshots comes from `refetchOnWindowFocus: true`).

If I set `staleTime: Infinity` then the 2nd fetch doesn't happen but then `refetchOnWindowFocus` doesn't get triggered anymore.

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/query/tree/main/examples/svelte/ssr?from-embed

### Steps to reproduce

Just follow the example at https://tanstack.com/query/latest/docs/svelte/examples/svelte/ssr

### Expected behavior

The query should not run a 2nd time

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/126693611/222182664-35c5ae6a-ba5f-4ccb-8f76-bae9b33fdbd1.png)

![image](https://user-images.githubusercontent.com/126693611/222182730-622e3165-2fe8-4ffe-af10-3c8bc0c369b7.png)

### Platform

- OS: macOS 13.0.1 
- Browser : all of them

### TanStack Query version

4.24.10

### TypeScript version

4.9.3

**Comment by liborvanek** [comment] 2023-03-05 21:49
I believe this is expected behaviour – according to the [documentation](https://tanstack.com/query/v4/docs/react/guides/ssr#staleness-is-measured-from-when-the-query-was-fetched-on-the-server), queries will be refetched in the background on page load because the `staleTime` is set to `0` by default. 
To avoid immediate refetch, set a higher value.

**Comment by universaltonton** [comment] 2023-03-06 09:03
Well that's kind of misleading then: the documentation for React and for Svelte seems to be contradictory.

The Svelte doc says:

_Svelte Query supports prefetching queries on the server. Using this setup below, you can fetch data and pass it into QueryClientProvider before it is sent to the user's browser. Therefore, this data is already available in the cache, and no initial fetch occurs client-side._

The code from the doc doesn't set `staleTime` at all.

**Comment by lachlancollins** [comment] 2023-03-10 12:45
@universaltonton good point, the wording is misleading - I guess I should mention `staleTime`, which isn't actually mentioned in the svelte-query docs.

I'm hesitant to include a specific value in the example directly - the other frameworks' docs use it sparingly, which I imagine is to let the user decide what is an appropriate `staleTime` for their specific project. However, I feel like adding a default to this example wouldn't be unreasonable provided I comment on its purpose.

**Comment by kevinrenskers** [comment] 2023-03-13 18:39
I just hit the exact same problem; I was very very surprised to see all queries getting done twice when we followed the docs. Where do we set this `staleTime` property? And yes please add this to the docs and examples.

**Comment by kevinrenskers** [comment] 2023-03-13 20:06
Found it, but even with these default options I am still seeing duplicate queries:

```
const queryClient = new QueryClient({
  queries: {
    enabled: browser,
    refetchOnWindowFocus: false,
    staleTime: Infinity,
  },
})
```

The problem is that the request is first made in SSR, and then again in the browser. So yes when you just look at the Network inspector in your browser you will see only one request to that `posts` endpoint when you set the `staleTime: Infinity` parameter, but when you control the server and can see the incoming requests, you will see two requests getting made, one right after the other.

Isn't SvelteQuery supposed to prevent that from happening?

**Comment by liborvanek** [comment] 2023-03-13 20:09
> Found it, but even with these default options I am still seeing duplicate queries:
> 
> ```
> const queryClient = new QueryClient({
>   queries: {
>     enabled: browser,
>     refetchOnWindowFocus: false,
>     staleTime: Infinity,
>   },
> })
> ```
> 
> The problem is that the request is first made in SSR, and then again in the browser. So yes when you just look at the Network inspector in your browser you will see only one request to that `posts` endpoint when you set the `staleTime: Infinity` parameter, but when you control the server and can see the incoming requests, you will see two requests getting made, one right after the other.
> 
> Isn't SvelteQuery supposed to prevent that from happening?

Try adding `refetchOnMount: false`.

**Comment by kevinrenskers** [comment] 2023-03-13 20:13
That doesn't help. FYI I used the https://tanstack.com/query/latest/docs/svelte/examples/svelte/ssr code, the only difference is I am using a local server just so I can see all the incoming requests.

**Comment by universaltonton** [comment] 2023-03-14 08:10
> @universaltonton good point, the wording is misleading - I guess I should mention `staleTime`, which isn't actually mentioned in the svelte-query docs.
> 
> I'm hesitant to include a specific value in the example directly - the other frameworks' docs use it sparingly, which I imagine is to let the user decide what is an appropriate `staleTime` for their specific project. However, I feel like adding a default to this example wouldn't be unreasonable provided I comment on its purpose.

I think a proper comment about the value of `staleTime` should do he trick.

**Comment by andrewbridge** [comment] 2023-04-01 18:40
I'm experiencing the same issue as @kevinrenskers. With the SSR set up as per the TanStack Svelte Query docs, plus setting the `staleTime` to `Infinity`, I'm seeing two calls to the endpoint I set in my `queryFn`:

- One with the `undici` user agent, which is presumably coming from the `prefetchQuery` call
- Another with a Google Chrome user agent, which I can see is coming from my browser

Both calls return the same data and happen within a second of one another, so I believe they're happening on first load on the server and client respectively.

This can be fixed by creating a `+page.server.ts` and making the same call there and returning the data:

`+page.server.ts`
```ts
import { getStuff } from '$lib/testApi';

/** @type {import('./$types').PageServerLoad} */
export async function load({ params }) {
    return {
      data: await getStuff()
    };
}
```
then conditionally running the `prefetchQuery` (although I'm no longer sure of its purpose here)

`+page.ts`
```ts
import { getStuff } from '$lib/testApi';
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ data, parent }) => {
  const { queryClient, ...rest } = await parent();
  if (!data.data) {
    await queryClient.prefetchQuery({
        queryKey: ['data'],
        queryFn: () => getStuff()
    });
  }
}
```

Now, because of the addition of `+page.server.ts`, the generated source includes this data on the page
<img width="470" alt="image" src="https://user-images.githubusercontent.com/2941908/229308113-958d0b8f-8d95-47f0-b02e-38b218c4b9bb.png">

Which is then available to the page to provide as `initialData`

`+page.svelte`
```svelte
<script>
    import { createQuery } from '@tanstack/svelte-query'
    import { getStuff } from '$lib/testApi';

    export let data;

    const client = createClient();
    const query = createQuery({
        queryKey: ['testData'],
        queryFn: () => getStuff(),
        initialData: data.data
    });
</script>

<!-- Do stuff -->
```

A single page load now produces a single request to the endpoint from the server, and that data is now shared with the client for reuse. However, this feels far messier than the docs suggest, is it expected behaviour for multiple requests to be made, or is the expected behaviour that the call made by `prefetchQuery` on the server is cached and passed to the client so the data can be reused?

**Comment by khongdudinhdoikhongne** [comment] 2023-04-02 03:18
I thought I'd set it up wrong somewhere and it wouldn't run as expected. After being here it seems to be a common problem.

**Comment by bevm0** [comment] 2023-04-07 13:48
It seems to work when using SvelteKit's custom fetch function provided to load functions. [Here's modified example of the original sandbox demonstrating this](https://codesandbox.io/p/sandbox/late-snow-yqfrmg?file=%2Fsrc%2Froutes%2F%2Bpage.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A12%7D%5D).

Here, `getPosts` accepts an optional `customFetch` argument, which defaults to the global `fetch` function when not provided. Maybe [the last bullet point](https://kit.svelte.dev/docs/load#making-fetch-requests) explains why it's able to cache the query properly in the query client with this approach?

Changes:
```ts 
// src/lib/getPosts.ts
export const getPosts = async (
  limit: number,
  customFetch: RequestEvent["fetch"] = fetch
) => {
  const response = await customFetch(
    "https://jsonplaceholder.typicode.com/posts"
  );
  const data = (await response.json()) as Post[];
  return data.filter((x) => x.id <= limit);
};

// src/routes/+page.ts
export const load: PageLoad = async ({ parent, fetch }) => {
  const { queryClient } = await parent()

  await queryClient.prefetchQuery({
    queryKey: ['posts', 10],
    queryFn: () => getPosts(10, fetch),
  })
}
```

**Comment by kevinrenskers** [comment] 2023-04-07 13:52
Strange, I'm also using the supplied fetch method with the prefetch (in `+page.ts`), but I am still seeing duplicate requests coming into the server.

**Comment by bevm0** [comment] 2023-04-07 14:05
I think that's because the data is immediately considered stale and it's doing a background refetch on mount to update it. To disable the refresh, you could set the `staleTime` > 0 or `refetchOnMount: false`. Do either of those help?

**Comment by kevinrenskers** [comment] 2023-04-07 14:08
Yeah, staleTime is set to 15 minutes. I'll get a repro up and running as soon as possible.

**Comment by lachlancollins** [comment] 2023-04-08 00:17
@bevm0 thanks for the solution!

**Closed** 2023-04-15 03:40 UTC
Labels: package: svelte-query

**Comment by gooonzick** [comment] 2024-06-28 22:27
Hi! I have read discussion and tried all offered solution, but I still have network requests in browser after prefetch data on server. Here is link to repo with reproduce
https://github.com/gooonzick/svelte-template
