### ISSUE TITLE
Doesn't work out of the box with next 13

### ISSUE THREAD

**Issue by JonasWijne** [TanStack/query#4933] opened 2023-02-03 21:39 UTC
### Describe the bug

when adding react-query to next 13 i get following error when running 
```
error - ./node_modules/@tanstack/react-query/build/lib/Hydrate.mjs
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./node_modules/@tanstack/react-query/build/lib/Hydrate.mjs
./node_modules/@tanstack/react-query/build/lib/index.mjs
./src/app/layout.tsx
```

code 
```
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";

const queryClient = new QueryClient()

/* ... */
      <QueryClientProvider client={queryClient}>
          {children}
      </QueryClientProvider>
/* ... */
```

### Your minimal, reproducible example

https://github.com/JonasWijne/next-test-react-query

### Steps to reproduce

1. git clone https://github.com/JonasWijne/next-test-react-query.git
2. cd  next-test-react-query
3. yarn
4. yarn dev
5. open browser to http://localhost:3000

### Expected behavior

as a user i expect it to compile/dev serve

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="965" alt="image" src="https://user-images.githubusercontent.com/6184820/216715641-944c5614-999a-46d3-bc71-abffc5b1e7ab.png">

### Platform

- OS: MacOS
- browser: chrome

### TanStack Query version

4.24.4

### TypeScript version

4.9.5

**Comment by Bknight010723** [comment] 2023-02-04 22:30
sdkmanager --uninstall --package_file #4939

**Comment by d4nyll** [comment] 2023-02-05 01:15
With Next.js 13's `app` directory feature, every component, by default, is a Server Component. Which means you are trying to use context in a Server Component, which is not supported. Instead, you should create a new Client Component (with `'use client';` directive), apply your context provider there (alongside any other context providers), and import that in your root layout.

```ts
'use client';

import { QueryClient, QueryClientProvider } from 'react-query'

const queryClient = new QueryClient()

export default function QueryProvider({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <QueryClientProvider client={queryClient}>
      {children}
    </QueryClientProvider>
  );
}
```

```ts

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  )
}
```

See [Using context in Client Components](https://beta.nextjs.org/docs/rendering/server-and-client-components#using-context-in-client-components) for more details.

**Comment by OrmEmbaar** [comment] 2023-02-08 21:12
I am seeing the same error. The TanStack docs [suggest](https://tanstack.com/query/v4/docs/react/guides/ssr#using-hydrate) creating the following singleton client on the server for import into server components, but that does not seem to work:

```typescript
import { QueryClient } from '@tanstack/react-query'
import { cache } from 'react'

const getQueryClient = cache(() => new QueryClient())
export default getQueryClient
```

I do not get that error with the `initialData` approach outlined in the docs. I am using Next `13.1.6` and react-query `4.24.4`.

**Comment by arzzzen** [comment] 2023-02-08 22:12
+1 have the same error after attempt to follow TanStack docs

**Comment by barbarah** [comment] 2023-02-09 10:38
I also cannot get it working with Hydrate, following the docs. It will work with the `initialData`.

I made a sandbox with a very simple Next 13 app and followed the readme for Next 13.

https://codesandbox.io/p/sandbox/silly-poincare-w6q5nk?selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A2%7D%5D

**Comment by TkDodo** [comment] 2023-02-12 08:31
The docs say you have to put the providers into a separate `app/providers.tsx` file that has `'use client'` at the top. I did that and it works, here's a fork of your reproduction:

https://codesandbox.io/p/sandbox/gracious-merkle-8lzrrk

**Comment by Talent30** [comment] 2023-02-14 07:24
> 文档说您必须将提供程序放入顶部的单独`app/providers.tsx`文件中。`'use client'`我这样做了并且有效，这是您的复制品的一个分支：
> 
> https://codesandbox.io/p/sandbox/gracious-merkle-8lzrrk

Yes, it works up to now but once you start using getQueryClient in server component you get the error `error - ../../node_modules/@tanstack/react-query/build/lib/Hydrate.mjs
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').`

**Comment by Talent30** [comment] 2023-02-14 07:25
> The docs say you have to put the providers into a separate `app/providers.tsx` file that has `'use client'` at the top. I did that and it works, here's a fork of your reproduction:
> 
> https://codesandbox.io/p/sandbox/gracious-merkle-8lzrrk

Yes, it works up to now but once you start using getQueryClient in server component you get the error `error - ../../node_modules/@tanstack/react-query/build/lib/Hydrate.mjs Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').`

**Comment by Talent30** [comment] 2023-02-14 07:44
@TkDodo 
demo: [https://codesandbox.io/p/sandbox/nice-faraday-txxprf](url)

**Comment by TkDodo** [comment] 2023-02-14 07:52
@Ephem do you know why this is happening? It seems like

`import { QueryClient } from "@tanstack/react-query";` brings in a lot more than just the `QueryClient`, as the error comes form `Hydrate.tsx`. Removing that import makes it work. However, `Hydrate.tsx` alone has the `'use client'` directive at the top 🤔

**Comment by Talent30** [comment] 2023-02-14 08:07
@TkDodo If you go to the Hydrate.esm.js output the 'use client' is not there for some reason, I am using v4.24.4

**Comment by Talent30** [comment] 2023-02-14 08:14
Can't upload img...

path: node_modules/@tanstack/react-query/build/lib/Hydrate.esm.js

line 1: import * as React from 'react';

**Comment by TkDodo** [comment] 2023-02-14 12:08
I think it could be this:
- https://github.com/rollup/rollup/issues/4699

probably we'd need to preserve the directive for esm builds?

**Comment by Talent30** [comment] 2023-02-15 04:18
> I think it could be this:
> 
> * ['use client' directive for Client Components rollup/rollup#4699](https://github.com/rollup/rollup/issues/4699)
> 
> probably we'd need to preserve the directive for esm builds?

The way suggested will add `'use client'` to every single file isn't it?

**Comment by TkDodo** [comment] 2023-02-15 07:24
> The way suggested will add 'use client' to every single file isn't it? Would it be harmful?

We have added `use client` to every file that needs it. When bundled together into one file, it should be removed, which is what rollup does. But for ESM builds, I think separate files are being kept, so we probably would need the `use client` directive there.

I'm gonna wait for some input from @Ephem if that's correct or not.

**Comment by Ephem** [comment] 2023-02-15 08:20
Busy days so will look at this in more detail soon, but I think you've definitely found the cause. Will need to think a bit on how this affects the different builds, can we even have a single entry point when with builds that bundle into a single file?

I think we ran into this during the docs-PR as well so at some point we recommended importing what you can from `import { QueryClient } from '@tanstack/query-core'` instead of `import { QueryClient } from '@tanstack/react-query'` which might still be a working workaround/fix.

**Comment by TkDodo** [comment] 2023-02-15 08:23
> importing what you can from import { QueryClient } from '@tanstack/query-core'

but for this, eslint will likely force you to have a direct dependency on `query-core`, which most people won't have. Also, if you add `query-core` as a dependency, you will wind up with two version of `query-core`, because `react-query` re-exports the core. Difficult topic 😅

**Comment by pixelmord** [comment] 2023-02-15 19:35
I ran into the same error 
```
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').

Import trace for requested module:
../../node_modules/.pnpm/@tanstack+react-query@4.24.6_biqbaboplfbrettd7655fr4n2y/node_modules/@tanstack/react-query/build/lib/Hydrate.mjs
```

To fix that I wrapped all components that imported from '@tanstack/react-query' in components that "use client" and imported all functions used in server components from '@tanstack/query-core'
e.g.
```
import { QueryClient, dehydrate } from '@tanstack/query-core';
```

**Comment by satnaing** [comment] 2023-02-16 15:26
> I also cannot get it working with Hydrate, following the docs. It does work with the `initialData`.
> 
> I made a sandbox with a very simple Next 13 app. I made two examples, one with initial data, and one with hydrate, by following the TanStack docs for Next 13. The hydrate code throws the error.
> 
> https://codesandbox.io/p/sandbox/silly-poincare-w6q5nk

@barbarah Have you already solved that problem?

I'm facing the same issue. I cannot prefetch data on server using `Hydrate` method. `initialData` along with prop drilling works though.
I'm doing the exact same thing according to [docs](https://tanstack.com/query/v4/docs/react/guides/ssr#using-initialdata-2)

**Comment by barbarah** [comment] 2023-02-16 18:38
Sorry, no. I've tried the different options mentioned above. But I did not get my sandbox working.

I did update the sandbox link because apparently, the link was not working: https://codesandbox.io/p/sandbox/next13-react-query-forked-h4qh77

**Comment by feledori** [comment] 2023-02-23 16:46
I got it working by doing these step:
1. Wrapping the Hydrate wrapper in a separate "use client" component
2. Importing QueryClient from @tanstack/query-core in the server singleton
3. Importing the dehydrate function from @tanstack/query-core as well.

@barbarah Here is the working [sandbox](https://codesandbox.io/p/sandbox/next13-app-react-query-stgw3e) with the changes I just mentioned.

**Comment by mk965** [comment] 2023-03-10 08:58
> I got it working by doing these step:
> 
> 1. Wrapping the Hydrate wrapper in a separate "use client" component
> 2. Importing QueryClient from @tanstack/query-core in the server singleton
> 3. Importing the dehydrate function from @tanstack/query-core as well.
> 
> @barbarah Here is the working [sandbox](https://codesandbox.io/p/sandbox/next13-app-react-query-stgw3e) with the changes I just mentioned.

@feledori 

Good job!
But in your demo "getPost" is run twice. Once on the server, once on the client.

**Comment by feledori** [comment] 2023-03-10 13:42
@mk965 Just updated the sandbox, you just have to disable revalidateOnMount for the hydrated useQuery hook.

**Comment by Ephem** [comment] 2023-03-11 15:02
I finally did some digging and thinking on this today and thought I'd document my findings:

* `"use client"` wont ever work in a bundled build with shared code. Either you include it at the top of the bundle for everything, or you don't. My suggestion:
  * We require/strongly recommend you use an unbundled build if you are using RSCs (this is what Next will use out of the box, so should be straightforward)
  * If we would want to have a workaround so bundled builds could work with RSCs, we could use the Rollup banner2 plugin to add "use client" at the top of the bundled builds, and document that in this case you need to do imports in RSCs from `@tanstack/query-core` instead of `@tanstack/react-query`. Not sure if it would work, but even if it did, I don't think this is something we should really support unless some very clear need arises.
* ~~The~~ One reason our _non_-bundled builds are currently failing on this is indeed the Rollup issue @TkDodo linked earlier: https://github.com/rollup/rollup/issues/4699
  * My hope is that preserving directives could be supported when the option `preserveModules: true` is set, that would let us fix this issue so everything works as in the current documentation, left a comment about this in the issue.
* Another reason builds are failing is even if you fix the above, builds are now(? Has this always been the case? Feels like something has changed here..) failing on _imports_ and not _usage_ of React "client" features, builds will fail on any server import of `@tanstack/react-query` since the index file is re-exporting things like `useQuery` that has a bunch of client-only features in it, but no `"use client"` at the top.
  * Note that not having `"use client"` at the top of those was intentional to have better error messages, these should never be imported from a server component, so only having `"use client"` at the top of component files gave better messages. I tested this myself, this is why it feels as if something has changed here..
  * Either way, to fix this we should just add back `"use client"` to the top of every file that uses React client only features in the `react-query` package.

I think we should:

- [ ] While we wait for the Rollup issue to unblock: Update the docs to the workaround @feledori documented above (basically what the docs @efilion contributed were before we added "use client" and rewrote them to remove `HydrateOnClient`).
- [ ] Add `"use client"` to the top of all files in `@tanstack/react-query` that imports something from React (all of them besides index?) (This wont fix anything until the Rollup issue is unblocked though)

**Comment by Ephem** [comment] 2023-03-11 15:16
Actually, what we _could_ do now as a temporary fix is add `"use client"` to the top of the entire react-query package with the Rollup banner2-plugin as documented in that issue (maybe only for the .mjs build?) and just document that on the server you have to use `@tanstack/query-core` for now? As long as you always use that only in RSCs, and always import from `@tanstack/react-query` elsewhere we shouldn't have a problem with duplicates right?

**Comment by Ephem** [comment] 2023-03-12 21:25
I got nerdsniped and built a Rollup plugin to preserve directives: https://github.com/Ephem/rollup-plugin-preserve-directives

I'll do some more testing, but with this I think we should be able to make it all work as per the docs.

**Closed** 2023-03-20 08:27 UTC

**Comment by TkDodo** [comment] 2023-03-20 08:39
please try it with:
- https://github.com/TanStack/query/releases/tag/v4.28.0

**Comment by mahdi-farnia** [comment] 2023-04-10 20:13
I did every thing including Provider file that has 'use client' directive and everything i found,
But it didn't work

Does this occurs because of next 13.3.0? (provided examples in this thread are using version 13.1.x)

**Comment by 2manoj1** [comment] 2023-04-13 12:42
Hello Everyone!
I made small POC with Next13 and React Query - Its working.
Have a look
[Example code](https://github.com/2manoj1/poc-nextjs-13-react-query)

Need a feedback or suggestion if any

**Comment by momenfc** [comment] 2023-05-16 00:06
try to import dehydrate from '@tanstack/query-core' instead  '@tanstack/react-query'
import { dehydrate } from '@tanstack/query-core';

**Comment by Schmale97** [comment] 2023-05-30 13:34
> I did every thing including Provider file that has 'use client' directive and everything i found, But it didn't work
> 
> Does this occurs because of next 13.3.0? (provided examples in this thread are using version 13.1.x)

I have also been able to get it to work with next version >=13.3.0 and @tanstack/* version 4.29.12

**Comment by Nishchit14** [comment] 2024-01-31 10:57
I just found the fix, In my case I was using one `valtio` function in `utils.ts` file which was used somewhere in the **server side api**.

Rule is if you're using any client side library then make sure that you're not using it's client apis/functions of library directly or indirectly on server routes or server actions.

**Comment by Franklivania** [comment] 2024-04-10 09:51
> I got it working by doing these step:
> 
>     1. Wrapping the Hydrate wrapper in a separate "use client" component
> 
>     2. Importing QueryClient from @tanstack/query-core in the server singleton
> 
>     3. Importing the dehydrate function from @tanstack/query-core as well.
> 
> 
> @barbarah Here is the working [sandbox](https://codesandbox.io/p/sandbox/next13-app-react-query-stgw3e) with the changes I just mentioned.

This worked, and this is an outline of what I am using


```
"@tanstack/react-query": "^4.29.7",
    "next": "13.5.6",
```
