### ISSUE TITLE
Error Boundary Error: A component suspended 

### ISSUE THREAD

**Issue by mohammad-aljamil** [TanStack/query#6951] opened 2024-02-22 13:28 UTC
### Describe the bug

 while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition. 

### Your minimal, reproducible example

no link

### Steps to reproduce

when go to page show this error ' while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition. '
showing after 5 minute when open again the page 

### Expected behavior

use enabled `    suspense: true`

### How often does this bug happen?

None

### Platform

mac os

### Tanstack Query adapter

None

### TanStack Query version

4.36.0

**Comment by TkDodo** [comment] 2024-02-24 10:50
closing because no reproduction. please invest a bit of time to create one, then I will invest time to looking into it.

**Closed by TkDodo** 2024-02-24 10:50 UTC
