### ISSUE TITLE
first tab queries not recorded - react native

### ISSUE THREAD

**Issue by anastely** [TanStack/query#4622] opened 2022-12-12 11:46 UTC
### Describe the bug

I'm trying to refetch data after some actions but it's not working,
So after using the `react-query-native-devtools` Debug tool, I can't see any query in the first tab recorded in the debug tool! Although the data fetched well.

So I guess that's why the refetch did not work in this case!

### Your minimal, reproducible example

https://stackoverflow.com/questions/74768738/refetching-queries-does-not-work-react-query

### Steps to reproduce

1- open App - Active Tab (first tab)
2- check the status of the queries 
3- nothing recorded in the debugger 
4- Navigate to any other screen/tab
5- Check the status of queries
6- all screen queries recorded in the debugger 

### Expected behavior

It should record all queries in the first tab so I can enable to refetch the queries

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/24620979/207036839-a44bc535-fe70-47ec-bcf1-2404e5f5a49d.mp4

### Platform

-OS [Android, iOS] 

### Tanstack Query version

v4.14.5

### TypeScript version

4.4.4

### Additional context

```
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.4",
    "react": "18.0.0",
    "react-native": "0.69.5",
```

**Comment by TkDodo** [comment] 2022-12-14 18:59
please show a real reproduction. The link to stackoverflow only shows a bunch of code.

**Comment by TkDodo** [comment] 2023-03-15 07:45
closing this because of missing reproduction

**Closed by TkDodo** 2023-03-15 07:45 UTC
Labels: needs-info, react-native
